UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 0;
UPDATE public."ClassJobCategory" SET name_cn = '所有职业', name_en = 'All Classes', name_jp = '全クラス' WHERE id = 1;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师', name_en = 'GLA', name_jp = '剣術士' WHERE id = 2;
UPDATE public."ClassJobCategory" SET name_cn = '格斗家', name_en = 'PGL', name_jp = '格闘士' WHERE id = 3;
UPDATE public."ClassJobCategory" SET name_cn = '斧术师', name_en = 'MRD', name_jp = '斧術士' WHERE id = 4;
UPDATE public."ClassJobCategory" SET name_cn = '枪术师', name_en = 'LNC', name_jp = '槍術士' WHERE id = 5;
UPDATE public."ClassJobCategory" SET name_cn = '弓箭手', name_en = 'ARC', name_jp = '弓術士' WHERE id = 6;
UPDATE public."ClassJobCategory" SET name_cn = '幻术师', name_en = 'CNJ', name_jp = '幻術士' WHERE id = 7;
UPDATE public."ClassJobCategory" SET name_cn = '咒术师', name_en = 'THM', name_jp = '呪術士' WHERE id = 8;
UPDATE public."ClassJobCategory" SET name_cn = '刻木匠', name_en = 'CRP', name_jp = '木工師' WHERE id = 9;
UPDATE public."ClassJobCategory" SET name_cn = '锻铁匠', name_en = 'BSM', name_jp = '鍛冶師' WHERE id = 10;
UPDATE public."ClassJobCategory" SET name_cn = '铸甲匠', name_en = 'ARM', name_jp = '甲冑師' WHERE id = 11;
UPDATE public."ClassJobCategory" SET name_cn = '雕金匠', name_en = 'GSM', name_jp = '彫金師' WHERE id = 12;
UPDATE public."ClassJobCategory" SET name_cn = '制革匠', name_en = 'LTW', name_jp = '革細工師' WHERE id = 13;
UPDATE public."ClassJobCategory" SET name_cn = '裁衣匠', name_en = 'WVR', name_jp = '裁縫師' WHERE id = 14;
UPDATE public."ClassJobCategory" SET name_cn = '炼金术士', name_en = 'ALC', name_jp = '錬金術師' WHERE id = 15;
UPDATE public."ClassJobCategory" SET name_cn = '烹调师', name_en = 'CUL', name_jp = '調理師' WHERE id = 16;
UPDATE public."ClassJobCategory" SET name_cn = '采矿工', name_en = 'MIN', name_jp = '採掘師' WHERE id = 17;
UPDATE public."ClassJobCategory" SET name_cn = '园艺工', name_en = 'BTN', name_jp = '園芸師' WHERE id = 18;
UPDATE public."ClassJobCategory" SET name_cn = '捕鱼人', name_en = 'FSH', name_jp = '漁師' WHERE id = 19;
UPDATE public."ClassJobCategory" SET name_cn = '骑士', name_en = 'PLD', name_jp = 'ナイト' WHERE id = 20;
UPDATE public."ClassJobCategory" SET name_cn = '武僧', name_en = 'MNK', name_jp = 'モンク' WHERE id = 21;
UPDATE public."ClassJobCategory" SET name_cn = '战士', name_en = 'WAR', name_jp = '戦士' WHERE id = 22;
UPDATE public."ClassJobCategory" SET name_cn = '龙骑士', name_en = 'DRG', name_jp = '竜騎士' WHERE id = 23;
UPDATE public."ClassJobCategory" SET name_cn = '吟游诗人', name_en = 'BRD', name_jp = '吟遊詩人' WHERE id = 24;
UPDATE public."ClassJobCategory" SET name_cn = '白魔法师', name_en = 'WHM', name_jp = '白魔道士' WHERE id = 25;
UPDATE public."ClassJobCategory" SET name_cn = '黑魔法师', name_en = 'BLM', name_jp = '黒魔道士' WHERE id = 26;
UPDATE public."ClassJobCategory" SET name_cn = '秘术师', name_en = 'ACN', name_jp = '巴術士' WHERE id = 27;
UPDATE public."ClassJobCategory" SET name_cn = '召唤师', name_en = 'SMN', name_jp = '召喚士' WHERE id = 28;
UPDATE public."ClassJobCategory" SET name_cn = '学者', name_en = 'SCH', name_jp = '学者' WHERE id = 29;
UPDATE public."ClassJobCategory" SET name_cn = '战斗精英', name_en = 'Disciple of War', name_jp = 'ファイター' WHERE id = 30;
UPDATE public."ClassJobCategory" SET name_cn = '魔法导师', name_en = 'Disciple of Magic', name_jp = 'ソーサラー' WHERE id = 31;
UPDATE public."ClassJobCategory" SET name_cn = '大地使者', name_en = 'Disciple of the Land', name_jp = 'ギャザラー' WHERE id = 32;
UPDATE public."ClassJobCategory" SET name_cn = '能工巧匠', name_en = 'Disciple of the Hand', name_jp = 'クラフター' WHERE id = 33;
UPDATE public."ClassJobCategory" SET name_cn = '战斗精英 魔法导师', name_en = 'Disciples of War or Magic', name_jp = 'ファイター ソーサラー' WHERE id = 34;
UPDATE public."ClassJobCategory" SET name_cn = '能工巧匠 大地使者', name_en = 'Disciples of the Land or Hand', name_jp = 'クラフター ギャザラー' WHERE id = 35;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师之外的战斗精英', name_en = 'Any Disciple of War (excluding gladiators)', name_jp = '剣術士を除くファイター' WHERE id = 36;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 格斗家 斧术师 枪术师 弓箭手 双剑师 幻术师 咒术师 秘术师 骑士 战士 暗黑骑士', name_en = 'GLA PGL MRD LNC ARC ROG CNJ THM ACN PLD WAR DRK', name_jp = '剣術士 格闘士 斧術士 槍術士 弓術士 双剣士 幻術士 呪術士 巴術士 ナイト 戦士 暗黒騎士' WHERE id = 37;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 骑士', name_en = 'GLA PLD', name_jp = '剣術士 ナイト' WHERE id = 38;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 格斗家 斧术师 枪术师 弓箭手 双剑师 骑士 战士 暗黑骑士', name_en = 'GLA PGL MRD LNC ARC ROG PLD WAR DRK', name_jp = '剣術士 格闘士 斧術士 槍術士 弓術士 双剣士 ナイト 戦士 暗黒騎士' WHERE id = 39;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 格斗家 斧术师 枪术师 弓箭手 双剑师 幻术师 咒术师 秘术师 武僧 战士 龙骑士 吟游诗人 忍者', name_en = 'GLA PGL MRD LNC ARC ROG CNJ THM ACN MNK WAR DRG BRD NIN', name_jp = '剣術士 格闘士 斧術士 槍術士 弓術士 双剣士 幻術士 呪術士 巴術士 モンク 戦士 竜騎士 吟遊詩人 忍者' WHERE id = 40;
UPDATE public."ClassJobCategory" SET name_cn = '格斗家 武僧', name_en = 'PGL MNK', name_jp = '格闘士 モンク' WHERE id = 41;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 格斗家 斧术师 枪术师 弓箭手 双剑师 武僧 战士 龙骑士 吟游诗人 忍者', name_en = 'GLA PGL MRD LNC ARC ROG MNK WAR DRG BRD NIN', name_jp = '剣術士 格闘士 斧術士 槍術士 弓術士 双剣士 モンク 戦士 竜騎士 吟遊詩人 忍者' WHERE id = 42;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 格斗家 斧术师 枪术师 弓箭手 双剑师 幻术师 咒术师 秘术师 骑士 武僧 战士 龙骑士 暗黑骑士', name_en = 'GLA PGL MRD LNC ARC ROG CNJ THM ACN PLD MNK WAR DRG DRK', name_jp = '剣術士 格闘士 斧術士 槍術士 弓術士 双剣士 幻術士 呪術士 巴術士 ナイト モンク 戦士 竜騎士 暗黒騎士' WHERE id = 43;
UPDATE public."ClassJobCategory" SET name_cn = '斧术师 战士', name_en = 'MRD WAR', name_jp = '斧術士 戦士' WHERE id = 44;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 格斗家 斧术师 枪术师 弓箭手 双剑师 骑士 武僧 战士 龙骑士 暗黑骑士', name_en = 'GLA PGL MRD LNC ARC ROG PLD MNK WAR DRG DRK', name_jp = '剣術士 格闘士 斧術士 槍術士 弓術士 双剣士 ナイト モンク 戦士 竜騎士 暗黒騎士' WHERE id = 45;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 格斗家 斧术师 枪术师 弓箭手 双剑师 幻术师 咒术师 秘术师 武僧 龙骑士 吟游诗人 忍者 机工士', name_en = 'GLA PGL MRD LNC ARC ROG CNJ THM ACN MNK DRG BRD NIN MCH', name_jp = '剣術士 格闘士 斧術士 槍術士 弓術士 双剣士 幻術士 呪術士 巴術士 モンク 竜騎士 吟遊詩人 忍者 機工士' WHERE id = 46;
UPDATE public."ClassJobCategory" SET name_cn = '枪术师 龙骑士', name_en = 'LNC DRG', name_jp = '槍術士 竜騎士' WHERE id = 47;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 格斗家 斧术师 枪术师 弓箭手 双剑师 武僧 龙骑士 吟游诗人 忍者 机工士', name_en = 'GLA PGL MRD LNC ARC ROG MNK DRG BRD NIN MCH', name_jp = '剣術士 格闘士 斧術士 槍術士 弓術士 双剣士 モンク 竜騎士 吟遊詩人 忍者 機工士' WHERE id = 48;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 格斗家 斧术师 枪术师 弓箭手 双剑师 幻术师 咒术师 秘术师 吟游诗人 黑魔法师 召唤师 机工士', name_en = 'GLA PGL MRD LNC ARC ROG CNJ THM ACN BRD BLM SMN MCH', name_jp = '剣術士 格闘士 斧術士 槍術士 弓術士 双剣士 幻術士 呪術士 巴術士 吟遊詩人 黒魔道士 召喚士 機工士' WHERE id = 49;
UPDATE public."ClassJobCategory" SET name_cn = '弓箭手 吟游诗人', name_en = 'ARC BRD', name_jp = '弓術士 吟遊詩人' WHERE id = 50;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 格斗家 斧术师 枪术师 弓箭手 双剑师 吟游诗人 机工士', name_en = 'GLA PGL MRD LNC ARC ROG BRD MCH', name_jp = '剣術士 格闘士 斧術士 槍術士 弓術士 双剣士 吟遊詩人 機工士' WHERE id = 51;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 格斗家 斧术师 枪术师 弓箭手 双剑师 幻术师 咒术师 秘术师 骑士 白魔法师 学者 占星术士', name_en = 'GLA PGL MRD LNC ARC ROG CNJ THM ACN PLD WHM SCH AST', name_jp = '剣術士 格闘士 斧術士 槍術士 弓術士 双剣士 幻術士 呪術士 巴術士 ナイト 白魔道士 学者 占星術師' WHERE id = 52;
UPDATE public."ClassJobCategory" SET name_cn = '幻术师 白魔法师', name_en = 'CNJ WHM', name_jp = '幻術士 白魔道士' WHERE id = 53;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 格斗家 斧术师 枪术师 弓箭手 双剑师 幻术师 咒术师 秘术师 白魔法师 黑魔法师 召唤师 学者 占星术士', name_en = 'GLA PGL MRD LNC ARC ROG CNJ THM ACN WHM BLM SMN SCH AST', name_jp = '剣術士 格闘士 斧術士 槍術士 弓術士 双剣士 幻術士 呪術士 巴術士 白魔道士 黒魔道士 召喚士 学者 占星術師' WHERE id = 54;
UPDATE public."ClassJobCategory" SET name_cn = '咒术师 黑魔法师', name_en = 'THM BLM', name_jp = '呪術士 黒魔道士' WHERE id = 55;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 幻术师 咒术师 骑士 白魔法师 黑魔法师', name_en = 'GLA CNJ THM PLD WHM BLM', name_jp = '剣術士 幻術士 呪術士 ナイト 白魔道士 黒魔道士' WHERE id = 56;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 咒术师 骑士 黑魔法师', name_en = 'GLA THM PLD BLM', name_jp = '剣術士 呪術士 ナイト 黒魔道士' WHERE id = 57;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 幻术师 骑士 白魔法师', name_en = 'GLA CNJ PLD WHM', name_jp = '剣術士 幻術士 ナイト 白魔道士' WHERE id = 58;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 斧术师 骑士 战士 暗黑骑士 绝枪战士', name_en = 'GLA MRD PLD WAR DRK GNB', name_jp = '剣術士 斧術士 ナイト 戦士 暗黒騎士 ガンブレイカー' WHERE id = 59;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 斧术师 枪术师 骑士 战士 龙骑士 暗黑骑士 绝枪战士 钐镰客', name_en = 'GLA MRD LNC PLD WAR DRG DRK GNB RPR', name_jp = '剣術士 斧術士 槍術士 ナイト 戦士 竜騎士 暗黒騎士 ガンブレイカー リーパー' WHERE id = 60;
UPDATE public."ClassJobCategory" SET name_cn = '幻术师 咒术师 秘术师 白魔法师 学者 占星术士', name_en = 'CNJ THM ACN WHM SCH AST', name_jp = '幻術士 呪術士 巴術士 白魔道士 学者 占星術師' WHERE id = 61;
UPDATE public."ClassJobCategory" SET name_cn = '幻术师 咒术师 秘术师 白魔法师 黑魔法师 召唤师 学者 占星术士', name_en = 'CNJ THM ACN WHM BLM SMN SCH AST', name_jp = '幻術士 呪術士 巴術士 白魔道士 黒魔道士 召喚士 学者 占星術師' WHERE id = 62;
UPDATE public."ClassJobCategory" SET name_cn = '咒术师 秘术师 黑魔法师 召唤师 赤魔法师 青魔法师', name_en = 'THM ACN BLM SMN RDM BLU', name_jp = '呪術士 巴術士 黒魔道士 召喚士 赤魔道士 青魔道士' WHERE id = 63;
UPDATE public."ClassJobCategory" SET name_cn = '幻术师 白魔法师 学者 占星术士 贤者', name_en = 'CNJ WHM SCH AST SGE', name_jp = '幻術士 白魔道士 学者 占星術師 賢者' WHERE id = 64;
UPDATE public."ClassJobCategory" SET name_cn = '格斗家 武僧 武士', name_en = 'PGL MNK SAM', name_jp = '格闘士 モンク 侍' WHERE id = 65;
UPDATE public."ClassJobCategory" SET name_cn = '弓箭手 吟游诗人 机工士 舞者', name_en = 'ARC BRD MCH DNC', name_jp = '弓術士 吟遊詩人 機工士 踊り子' WHERE id = 66;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 格斗家 斧术师 枪术师 双剑师 武僧 龙骑士 忍者', name_en = 'GLA PGL MRD LNC ROG MNK DRG NIN', name_jp = '剣術士 格闘士 斧術士 槍術士 双剣士 モンク 竜騎士 忍者' WHERE id = 67;
UPDATE public."ClassJobCategory" SET name_cn = '秘术师 召唤师 学者', name_en = 'ACN SMN SCH', name_jp = '巴術士 召喚士 学者' WHERE id = 68;
UPDATE public."ClassJobCategory" SET name_cn = '秘术师 召唤师', name_en = 'ACN SMN', name_jp = '巴術士 召喚士' WHERE id = 69;
UPDATE public."ClassJobCategory" SET name_cn = '烹调师之外的能工巧匠', name_en = 'Any Disciple of the Hand (excluding culinarians)', name_jp = '調理師以外のクラフター' WHERE id = 70;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 格斗家 斧术师 枪术师 弓箭手 双剑师 幻术师 咒术师 秘术师 白魔法师 黑魔法师 召唤师 学者', name_en = 'GLA PGL MRD LNC ARC ROG CNJ THM ACN WHM BLM SMN SCH', name_jp = '剣術士 格闘士 斧術士 槍術士 弓術士 双剣士 幻術士 呪術士 巴術士 白魔道士 黒魔道士 召喚士 学者' WHERE id = 71;
UPDATE public."ClassJobCategory" SET name_cn = '幻术师 咒术师 秘术师 白魔法师 黑魔法师 召唤师 学者', name_en = 'CNJ THM ACN WHM BLM SMN SCH', name_jp = '幻術士 呪術士 巴術士 白魔道士 黒魔道士 召喚士 学者' WHERE id = 72;
UPDATE public."ClassJobCategory" SET name_cn = '幻术师 白魔法师 学者 占星术士 贤者', name_en = 'CNJ WHM SCH AST SGE', name_jp = '幻術士 白魔道士 学者 占星術師 賢者' WHERE id = 73;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 74;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 75;
UPDATE public."ClassJobCategory" SET name_cn = '枪术师 龙骑士 钐镰客', name_en = 'LNC DRG RPR', name_jp = '槍術士 竜騎士 リーパー' WHERE id = 76;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 77;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 78;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 79;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 80;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 81;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 82;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 83;
UPDATE public."ClassJobCategory" SET name_cn = '格斗家 枪术师 武僧 龙骑士 武士 钐镰客', name_en = 'PGL LNC MNK DRG SAM RPR', name_jp = '格闘士 槍術士 モンク 竜騎士 侍 リーパー' WHERE id = 84;
UPDATE public."ClassJobCategory" SET name_cn = '战斗精英 魔法导师 特职专用', name_en = 'Jobs of the Disciples of War or Magic', name_jp = 'ファイター ソーサラー ジョブ専用' WHERE id = 85;
UPDATE public."ClassJobCategory" SET name_cn = '骑士 战士 暗黑骑士 绝枪战士 武僧 龙骑士 忍者 武士', name_en = 'PLD WAR DRK GNB MNK DRG NIN SAM', name_jp = 'ナイト 戦士 暗黒騎士 ガンブレイカー モンク 竜騎士 忍者 侍' WHERE id = 86;
UPDATE public."ClassJobCategory" SET name_cn = '吟游诗人 机工士 舞者 黑魔法师 召唤师 赤魔法师 白魔法师 学者 占星术士', name_en = 'BRD MCH DNC BLM SMN RDM WHM SCH AST', name_jp = '吟遊詩人 機工士 踊り子 黒魔道士 召喚士 赤魔道士 白魔道士 学者 占星術師' WHERE id = 87;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 斧术师 格斗家 枪术师 弓箭手 双剑师 骑士 武僧 战士 龙骑士 吟游诗人 忍者 暗黑骑士 机工士', name_en = 'GLA MRD PGL LNC ARC ROG PLD MNK WAR DRG BRD NIN MCH', name_jp = '剣術士 斧術士 格闘士 槍術士 弓術士 双剣士 ナイト モンク 戦士 竜騎士 吟遊詩人 忍者 暗黒騎士 機工士' WHERE id = 88;
UPDATE public."ClassJobCategory" SET name_cn = '黑魔法师 召唤师 赤魔法师', name_en = 'BLM SMN RDM', name_jp = '黒魔道士 召喚士 赤魔道士' WHERE id = 89;
UPDATE public."ClassJobCategory" SET name_cn = '弓箭手 幻术师 咒术师 秘术师 白魔法师 吟游诗人 黑魔法师 召唤师 学者 机工士 占星术士', name_en = 'ARC CNJ THM ACN WHM BRD BLM SMN SCH MCH AST', name_jp = '弓術士 幻術士 呪術士 巴術士 白魔道士 吟遊詩人 黒魔道士 召喚士 学者 機工士 占星術師' WHERE id = 90;
UPDATE public."ClassJobCategory" SET name_cn = '双剑师', name_en = 'ROG', name_jp = '双剣士' WHERE id = 91;
UPDATE public."ClassJobCategory" SET name_cn = '忍者', name_en = 'NIN', name_jp = '忍者' WHERE id = 92;
UPDATE public."ClassJobCategory" SET name_cn = '双剑师  忍者', name_en = 'ROG NIN', name_jp = '双剣士 忍者' WHERE id = 93;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 格斗家 斧术师 枪术师 弓箭手 双剑师 忍者', name_en = 'GLA PGL MRD LNC ARC ROG NIN', name_jp = '剣術士 格闘士 斧術士 槍術士 弓術士 双剣士 忍者' WHERE id = 94;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 格斗家 斧术师 枪术师 双剑师 忍者', name_en = 'GLA PGL MRD LNC ROG NIN', name_jp = '剣術士 格闘士 斧術士 槍術士 双剣士 忍者' WHERE id = 95;
UPDATE public."ClassJobCategory" SET name_cn = '机工士', name_en = 'MCH', name_jp = '機工士' WHERE id = 96;
UPDATE public."ClassJobCategory" SET name_cn = '格斗家 枪术师 弓箭手 双剑师 武僧 龙骑士 吟游诗人 忍者 机工士', name_en = 'PGL LNC ARC ROG MNK DRG BRD NIN MCH', name_jp = '格闘士 槍術士 弓術士 双剣士 モンク 竜騎士 吟遊詩人 忍者 機工士' WHERE id = 97;
UPDATE public."ClassJobCategory" SET name_cn = '暗黑骑士', name_en = 'DRK', name_jp = '暗黒騎士' WHERE id = 98;
UPDATE public."ClassJobCategory" SET name_cn = '占星术士', name_en = 'AST', name_jp = '占星術師' WHERE id = 99;
UPDATE public."ClassJobCategory" SET name_cn = '弓箭手 双剑师 吟游诗人 忍者 机工士', name_en = 'ARC ROG BRD NIN MCH', name_jp = '弓術士 双剣士 吟遊詩人 忍者 機工士' WHERE id = 100;
UPDATE public."ClassJobCategory" SET name_cn = '格斗家 枪术师 双剑师 武僧 龙骑士 忍者', name_en = 'PGL LNC ROG MNK DRG NIN', name_jp = '格闘士 槍術士 双剣士 モンク 竜騎士 忍者' WHERE id = 101;
UPDATE public."ClassJobCategory" SET name_cn = '格斗家 双剑师 武僧 忍者 武士', name_en = 'PGL ROG MNK NIN SAM', name_jp = '格闘士 双剣士 モンク 忍者 侍' WHERE id = 102;
UPDATE public."ClassJobCategory" SET name_cn = '双剑师  忍者', name_en = 'ROG NIN', name_jp = '双剣士 忍者' WHERE id = 103;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 104;
UPDATE public."ClassJobCategory" SET name_cn = '弓箭手 双剑师 吟游诗人 忍者 机工士 舞者', name_en = 'ARC ROG BRD NIN MCH DNC', name_jp = '弓術士 双剣士 吟遊詩人 忍者 機工士 踊り子' WHERE id = 105;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 格斗家 斧术师 枪术师 弓箭手 双剑师 吟游诗人', name_en = 'GLA MRD PGL LNC ARC ROG BRD', name_jp = '剣術士 格闘士 斧術士 槍術士 弓術士 双剣士 吟遊詩人' WHERE id = 106;
UPDATE public."ClassJobCategory" SET name_cn = '骑士 武僧 战士 龙骑士 吟游诗人 白魔法师 黑魔法师 召唤师 学者 忍者 机工士 暗黑骑士 占星术士', name_en = 'PLD MNK WAR DRG BRD WHM BLM SMN SCH NIN MCH DRK AST', name_jp = 'ナイト モンク 戦士 竜騎士 吟遊詩人 白魔道士 黒魔道士 召喚士 学者 忍者 機工士 暗黒騎士 占星術師' WHERE id = 107;
UPDATE public."ClassJobCategory" SET name_cn = '战斗精英 魔法导师', name_en = 'Disciples of War or Magic', name_jp = 'ファイター ソーサラー' WHERE id = 108;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 109;
UPDATE public."ClassJobCategory" SET name_cn = '战斗精英 魔法导师 特职专用', name_en = 'Jobs of the Disciples of War or Magic', name_jp = 'ファイター ソーサラー ジョブ専用' WHERE id = 110;
UPDATE public."ClassJobCategory" SET name_cn = '武士', name_en = 'SAM', name_jp = '侍' WHERE id = 111;
UPDATE public."ClassJobCategory" SET name_cn = '赤魔法师', name_en = 'RDM', name_jp = '赤魔道士' WHERE id = 112;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 斧术师 骑士 战士 暗黑骑士 绝枪战士', name_en = 'GLA MRD PLD WAR DRK GNB', name_jp = '剣術士 斧術士 ナイト 戦士 暗黒騎士 ガンブレイカー' WHERE id = 113;
UPDATE public."ClassJobCategory" SET name_cn = '格斗家 枪术师 武僧 龙骑士 双剑师 忍者 武士 钐镰客', name_en = 'PGL LNC ROG MNK DRG NIN SAM RPR', name_jp = '格闘士 槍術士 モンク 竜騎士 双剣士 忍者 侍 リーパー' WHERE id = 114;
UPDATE public."ClassJobCategory" SET name_cn = '弓箭手 吟游诗人 机工士 舞者', name_en = 'ARC BRD MCH DNC', name_jp = '弓術士 吟遊詩人 機工士 踊り子' WHERE id = 115;
UPDATE public."ClassJobCategory" SET name_cn = '咒术师 黑魔法师 秘术师 召唤师 赤魔法师 青魔法师', name_en = 'THM ACN BLM SMN RDM BLU', name_jp = '呪術士 黒魔道士 巴術士 召喚士 赤魔道士 青魔道士' WHERE id = 116;
UPDATE public."ClassJobCategory" SET name_cn = '幻术师 白魔法师 学者 占星术士 贤者', name_en = 'CNJ WHM SCH AST SGE', name_jp = '幻術士 白魔道士 学者 占星術師 賢者' WHERE id = 117;
UPDATE public."ClassJobCategory" SET name_cn = '格斗家 枪术师 弓箭手 武僧 龙骑士 吟游诗人 双剑师 忍者 机工士 武士 舞者 钐镰客', name_en = 'PGL LNC ARC ROG MNK DRG BRD NIN MCH SAM DNC RPR', name_jp = '格闘士 槍術士 弓術士 モンク 竜騎士 吟遊詩人 双剣士 忍者 機工士 侍 踊り子 リーパー' WHERE id = 118;
UPDATE public."ClassJobCategory" SET name_cn = '格斗家 枪术师 咒术师 武僧 龙骑士 黑魔法师 秘术师 召唤师 双剑师 忍者 武士 赤魔法师 青魔法师 钐镰客', name_en = 'PGL LNC THM ACN ROG MNK DRG BLM SMN NIN SAM RDM BLU RPR', name_jp = '格闘士 槍術士 呪術士 モンク 竜騎士 黒魔道士 巴術士 召喚士 双剣士 忍者 侍 赤魔道士 青魔道士 リーパー' WHERE id = 119;
UPDATE public."ClassJobCategory" SET name_cn = '幻术师 咒术师 白魔法师 黑魔法师 秘术师 召唤师 学者 占星术士 赤魔法师 青魔法师 贤者', name_en = 'CNJ THM ACN WHM BLM SMN SCH AST RDM BLU SGE', name_jp = '幻術士 呪術士 白魔道士 黒魔道士 巴術士 召喚士 学者 占星術師 赤魔道士 青魔道士 賢者' WHERE id = 120;
UPDATE public."ClassJobCategory" SET name_cn = '骑士 战士 暗黑骑士 绝枪战士', name_en = 'PLD WAR DRK GNB', name_jp = 'ナイト 戦士 暗黒騎士 ガンブレイカー' WHERE id = 121;
UPDATE public."ClassJobCategory" SET name_cn = '武僧 龙骑士 忍者 武士 钐镰客', name_en = 'MNK DRG NIN SAM RPR', name_jp = 'モンク 竜騎士 忍者 侍 リーパー' WHERE id = 122;
UPDATE public."ClassJobCategory" SET name_cn = '吟游诗人 机工士 舞者', name_en = 'BRD MCH DNC', name_jp = '吟遊詩人 機工士 踊り子' WHERE id = 123;
UPDATE public."ClassJobCategory" SET name_cn = '黑魔法师 召唤师 赤魔法师 青魔法师', name_en = 'BLM SMN RDM BLU', name_jp = '黒魔道士 召喚士 赤魔道士 青魔道士' WHERE id = 124;
UPDATE public."ClassJobCategory" SET name_cn = '白魔法师 学者 占星术士 贤者', name_en = 'WHM SCH AST SGE', name_jp = '白魔道士 学者 占星術師 賢者' WHERE id = 125;
UPDATE public."ClassJobCategory" SET name_cn = '武僧 龙骑士 吟游诗人 忍者 机工士 武士 舞者 钐镰客', name_en = 'MNK DRG BRD NIN MCH SAM DNC RPR', name_jp = 'モンク 竜騎士 吟遊詩人 忍者 機工士 侍 踊り子 リーパー' WHERE id = 126;
UPDATE public."ClassJobCategory" SET name_cn = '武僧 龙骑士 黑魔法师 召唤师 忍者 武士 赤魔法师 青魔法师 钐镰客', name_en = 'MNK DRG BLM SMN NIN SAM RDM BLU RPR', name_jp = 'モンク 竜騎士 黒魔道士 召喚士 忍者 侍 赤魔道士 青魔道士 リーパー' WHERE id = 127;
UPDATE public."ClassJobCategory" SET name_cn = '白魔法师 黑魔法师 召唤师 学者 占星术士 赤魔法师 青魔法师 贤者', name_en = 'WHM BLM SMN SCH AST RDM BLU SGE', name_jp = '白魔道士 黒魔道士 召喚士 学者 占星術師 赤魔道士 青魔道士 賢者' WHERE id = 128;
UPDATE public."ClassJobCategory" SET name_cn = '青魔法师', name_en = 'BLU', name_jp = '青魔道士' WHERE id = 129;
UPDATE public."ClassJobCategory" SET name_cn = '所有（除设限特职）', name_en = 'All classes and jobs (excluding limited jobs)', name_jp = 'すべて (リミテッドジョブを除く)' WHERE id = 130;
UPDATE public."ClassJobCategory" SET name_cn = '武僧 龙骑士 吟游诗人 黑魔法师 召唤师 忍者 机工士 武士 赤魔法师 舞者 钐镰客', name_en = 'MNK DRG BRD BLM SMN NIN MCH SAM RDM DNC RPR', name_jp = 'モンク 竜騎士 吟遊詩人 黒魔道士 召喚士 忍者 機工士 侍 赤魔道士 踊り子 リーパー' WHERE id = 131;
UPDATE public."ClassJobCategory" SET name_cn = '武僧 龙骑士 吟游诗人 白魔法师 黑魔法师 召唤师 学者 忍者 机工士 占星术士 武士 赤魔法师 舞者 钐镰客 贤者', name_en = 'MNK DRG BRD WHM BLM SMN SCH NIN MCH AST SAM RDM DNC RPR SGE', name_jp = 'モンク 竜騎士 吟遊詩人 白魔道士 黒魔道士 召喚士 学者 忍者 機工士 占星術師 侍 赤魔道士 踊り子 リーパー 賢者' WHERE id = 132;
UPDATE public."ClassJobCategory" SET name_cn = '白魔法师 学者 占星术士 贤者', name_en = 'WHM SCH AST SGE', name_jp = '白魔道士 学者 占星術師 賢者' WHERE id = 133;
UPDATE public."ClassJobCategory" SET name_cn = '骑士 战士 暗黑骑士 绝枪战士', name_en = 'PLD WAR DRK GNB', name_jp = 'ナイト 戦士 暗黒騎士 ガンブレイカー' WHERE id = 134;
UPDATE public."ClassJobCategory" SET name_cn = '骑士 武僧 战士 龙骑士 吟游诗人 黑魔法师 召唤师 忍者 机工士 暗黑骑士 武士 赤魔法师 绝枪战士 舞者 钐镰客', name_en = 'PLD MNK WAR DRG BRD BLM SMN NIN MCH DRK SAM RDM GNB DNC RPR', name_jp = 'ナイト モンク 戦士 竜騎士 吟遊詩人 黒魔道士 召喚士 忍者 機工士 暗黒騎士 侍 赤魔道士 ガンブレイカー 踊り子 リーパー' WHERE id = 135;
UPDATE public."ClassJobCategory" SET name_cn = '骑士 战士 白魔法师 学者 暗黑骑士 占星术士 绝枪战士 贤者', name_en = 'PLD WAR WHM SCH DRK AST GNB SGE', name_jp = 'ナイト 戦士 白魔道士 学者 暗黒騎士 占星術師 ガンブレイカー 賢者' WHERE id = 136;
UPDATE public."ClassJobCategory" SET name_cn = '骑士 武僧 战士 龙骑士 吟游诗人 白魔法师 黑魔法师 召唤师 学者 忍者 机工士 暗黑骑士 占星术士 武士 赤魔法师 绝枪战士 舞者 钐镰客 贤者', name_en = 'PLD MNK WAR DRG BRD WHM BLM SMN SCH NIN MCH DRK AST SAM RDM GNB DNC RPR SGE', name_jp = 'ナイト モンク 戦士 竜騎士 吟遊詩人 白魔道士 黒魔道士 召喚士 学者 忍者 機工士 暗黒騎士 占星術師 侍 赤魔道士 ガンブレイカー 踊り子 リーパー 賢者' WHERE id = 137;
UPDATE public."ClassJobCategory" SET name_cn = '骑士 武僧 战士 龙骑士 忍者 暗黑骑士 武士 绝枪战士 钐镰客', name_en = 'PLD MNK WAR DRG NIN DRK SAM GNB RPR', name_jp = 'ナイト モンク 戦士 竜騎士 忍者 暗黒騎士 侍 ガンブレイカー リーパー' WHERE id = 138;
UPDATE public."ClassJobCategory" SET name_cn = '吟游诗人 机工士 舞者', name_en = 'BRD MCH DNC', name_jp = '吟遊詩人 機工士 踊り子' WHERE id = 139;
UPDATE public."ClassJobCategory" SET name_cn = '白魔法师 黑魔法师 召唤师 学者 占星术士 赤魔法师 贤者', name_en = 'WHM BLM SMN SCH AST RDM SGE', name_jp = '白魔道士 黒魔道士 召喚士 学者 占星術師 赤魔道士 賢者' WHERE id = 140;
UPDATE public."ClassJobCategory" SET name_cn = '骑士 武僧 战士 龙骑士 吟游诗人 白魔法师 黑魔法师 召唤师 学者 机工士 暗黑骑士 占星术士 武士 赤魔法师 绝枪战士 舞者 钐镰客 贤者', name_en = 'PLD MNK WAR DRG BRD WHM BLM SMN SCH MCH DRK AST SAM RDM GNB DNC RPR SGE', name_jp = 'ナイト モンク 戦士 竜騎士 吟遊詩人 白魔道士 黒魔道士 召喚士 学者 機工士 暗黒騎士 占星術師 侍 赤魔道士 ガンブレイカー 踊り子 リーパー 賢者' WHERE id = 141;
UPDATE public."ClassJobCategory" SET name_cn = '战斗精英和魔法导师（除设限特职）', name_en = 'Any Disciple of War or Magic (excluding limited jobs)', name_jp = 'ファイターとソーサラー (リミテッドジョブを除く)' WHERE id = 142;
UPDATE public."ClassJobCategory" SET name_cn = '战斗精英（除设限特职）', name_en = 'Disciples of War (excluding limited jobs)', name_jp = 'ファイター (リミテッドジョブを除く)' WHERE id = 143;
UPDATE public."ClassJobCategory" SET name_cn = '魔法导师（除设限特职）', name_en = 'Any Disciple of Magic (excluding limited jobs)', name_jp = 'ソーサラー (リミテッドジョブを除く)' WHERE id = 144;
UPDATE public."ClassJobCategory" SET name_cn = '骑士 武僧 战士 龙骑士 吟游诗人 忍者 机工士 暗黑骑士 武士 绝枪战士 舞者 钐镰客', name_en = 'PLD MNK WAR DRG BRD NIN MCH DRK SAM GNB DNC RPR', name_jp = 'ナイト モンク 戦士 竜騎士 吟遊詩人 忍者 機工士 暗黒騎士 侍 ガンブレイカー 踊り子 リーパー' WHERE id = 145;
UPDATE public."ClassJobCategory" SET name_cn = '战斗精英 魔法导师 特职专用（除设限特职）', name_en = 'Any job of the Disciples of War or Magic (excluding limited jobs)', name_jp = 'ファイター ソーサラー ジョブ専用 (リミテッドジョブを除く)' WHERE id = 146;
UPDATE public."ClassJobCategory" SET name_cn = '黑魔法师 召唤师 赤魔法师', name_en = 'BLM SMN RDM', name_jp = '黒魔道士 召喚士 赤魔道士' WHERE id = 147;
UPDATE public."ClassJobCategory" SET name_cn = '武僧 龙骑士 忍者 武士 钐镰客', name_en = 'MNK DRG NIN SAM RPR', name_jp = 'モンク 竜騎士 忍者 侍 リーパー' WHERE id = 148;
UPDATE public."ClassJobCategory" SET name_cn = '绝枪战士', name_en = 'GNB', name_jp = 'ガンブレイカー' WHERE id = 149;
UPDATE public."ClassJobCategory" SET name_cn = '舞者', name_en = 'DNC', name_jp = '踊り子' WHERE id = 150;
UPDATE public."ClassJobCategory" SET name_cn = '锻铁匠、铸甲匠、雕金匠', name_en = 'BSM, ARM, GSM', name_jp = '鍛冶師、甲冑師、彫金師' WHERE id = 151;
UPDATE public."ClassJobCategory" SET name_cn = '刻木匠、制革匠、裁衣匠', name_en = 'CRP, LTW, WVR', name_jp = '木工師、革細工師、裁縫師' WHERE id = 152;
UPDATE public."ClassJobCategory" SET name_cn = '炼金术士、烹调师', name_en = 'ALC, CUL', name_jp = '錬金術師、調理師' WHERE id = 153;
UPDATE public."ClassJobCategory" SET name_cn = '采矿工、园艺工', name_en = 'MIN, BTN', name_jp = '採掘師、園芸師' WHERE id = 154;
UPDATE public."ClassJobCategory" SET name_cn = '捕鱼人', name_en = 'FSH', name_jp = '漁師' WHERE id = 155;
UPDATE public."ClassJobCategory" SET name_cn = '防护职业（设限特职除外）', name_en = 'Tank (excluding limited jobs)', name_jp = 'TANKジョブ(リミテッドジョブを除く)' WHERE id = 156;
UPDATE public."ClassJobCategory" SET name_cn = '治疗职业（设限特职除外）', name_en = 'Healer (excluding limited jobs)', name_jp = 'HEALERジョブ (リミテッドジョブを除く)' WHERE id = 157;
UPDATE public."ClassJobCategory" SET name_cn = '物理进攻职业（设限特职除外）', name_en = 'Physical DPS (excluding limited jobs)', name_jp = 'ファイター系DPSジョブ(リミテッドジョブを除く)' WHERE id = 158;
UPDATE public."ClassJobCategory" SET name_cn = '魔法进攻职业（设限特职除外）', name_en = 'Magical Ranged DPS (excluding limited jobs)', name_jp = 'ソーサラー系DPSジョブ (リミテッドジョブを除く)' WHERE id = 159;
UPDATE public."ClassJobCategory" SET name_cn = '秘术师 学者', name_en = 'ACN SCH', name_jp = '巴術士 学者' WHERE id = 160;
UPDATE public."ClassJobCategory" SET name_cn = '剑术师 格斗家 斧术师 枪术师 弓箭手 骑士 武僧 战士 龙骑士 吟游诗人 双剑师 忍者 机工士 暗黑骑士 武士 绝枪战士 舞者 钐镰客', name_en = 'GLA PGL MRD LNC ARC PLD MNK WAR DRG BRD ROG NIN MCH DRK SAM GNB DNC RPR', name_jp = '剣術士 格闘士 斧術士 槍術士 弓術士 ナイト モンク 戦士 竜騎士 吟遊詩人 双剣士 忍者 機工士 暗黒騎士 侍 ガンブレイカー 踊り子 リーパー' WHERE id = 161;
UPDATE public."ClassJobCategory" SET name_cn = '骑士 武僧 战士 龙骑士 吟游诗人 白魔法师 黑魔法师 召唤师 学者 
忍者 机工士 暗黑骑士 占星术士 武士 赤魔法师 绝枪战士 舞者', name_en = 'PLD MNK WAR DRG BRD WHM BLM SMN SCH NIN MCH DRK AST SAM RDM GNB DNC', name_jp = 'ナイト モンク 戦士 竜騎士 吟遊詩人 白魔道士 黒魔道士 召喚士 学者 
忍者 機工士 暗黒騎士 占星術師 侍 赤魔道士 ガンブレイカー 踊り子' WHERE id = 162;
UPDATE public."ClassJobCategory" SET name_cn = '武僧 龙骑士 吟游诗人 黑魔法师 召唤师 忍者 机工士 武士 赤魔法师 舞者 钐镰客', name_en = 'MNK DRG BRD BLM SMN NIN MCH SAM RDM DNC RPR', name_jp = 'モンク 竜騎士 吟遊詩人 黒魔道士 召喚士 忍者 機工士 侍 赤魔道士 踊り子 リーパー' WHERE id = 163;
UPDATE public."ClassJobCategory" SET name_cn = '武僧 龙骑士 吟游诗人 白魔法师 黑魔法师 召唤师 学者 忍者 机工士 占星术士 武士 赤魔法师 舞者 钐镰客 贤者', name_en = 'MNK DRG BRD WHM BLM SMN SCH NIN MCH AST SAM RDM DNC RPR SGE', name_jp = 'モンク 竜騎士 吟遊詩人 白魔道士 黒魔道士 召喚士 学者 忍者 機工士 占星術師 侍 赤魔道士 踊り子 リーパー 賢者' WHERE id = 164;
UPDATE public."ClassJobCategory" SET name_cn = '白魔法师 学者 占星术士 贤者', name_en = 'WHM SCH AST SGE', name_jp = '白魔道士 学者 占星術師 賢者' WHERE id = 165;
UPDATE public."ClassJobCategory" SET name_cn = '骑士 战士 暗黑骑士 绝枪战士', name_en = 'PLD WAR DRK GNB', name_jp = 'ナイト 戦士 暗黒騎士 ガンブレイカー' WHERE id = 166;
UPDATE public."ClassJobCategory" SET name_cn = '骑士 武僧 战士 龙骑士 吟游诗人 黑魔法师 召唤师 忍者 机工士 暗黑骑士 武士 赤魔法师 绝枪战士 舞者 钐镰客', name_en = 'PLD MNK WAR DRG BRD BLM SMN NIN MCH DRK SAM RDM GNB DNC RPR', name_jp = 'ナイト モンク 戦士 竜騎士 吟遊詩人 黒魔道士 召喚士 忍者 機工士 暗黒騎士 侍 赤魔道士 ガンブレイカー 踊り子 リーパー' WHERE id = 167;
UPDATE public."ClassJobCategory" SET name_cn = '骑士 战士 白魔法师 学者 暗黑骑士 占星术士 绝枪战士 贤者', name_en = 'PLD WAR WHM SCH DRK AST GNB SGE', name_jp = 'ナイト 戦士 白魔道士 学者 暗黒騎士 占星術師 ガンブレイカー 賢者' WHERE id = 168;
UPDATE public."ClassJobCategory" SET name_cn = '骑士 武僧 战士 龙骑士 吟游诗人 白魔法师 黑魔法师 召唤师 学者 忍者 机工士 暗黑骑士 占星术士 武士 赤魔法师 绝枪战士 舞者 钐镰客 贤者', name_en = 'PLD MNK WAR DRG BRD WHM BLM SMN SCH NIN MCH DRK AST SAM RDM GNB DNC RPR SGE', name_jp = 'ナイト モンク 戦士 竜騎士 吟遊詩人 白魔道士 黒魔道士 召喚士 学者 忍者 機工士 暗黒騎士 占星術師 侍 赤魔道士 ガンブレイカー 踊り子 リーパー 賢者' WHERE id = 169;
UPDATE public."ClassJobCategory" SET name_cn = 'ナイト モンク 戦士 竜騎士 忍者 暗黒騎士 侍 ガンブレイカー リーパー', name_en = 'PLD MNK WAR DRG NIN DRK SAM GNB RPR', name_jp = 'ナイト モンク 戦士 竜騎士 忍者 暗黒騎士 侍 ガンブレイカー リーパー' WHERE id = 170;
UPDATE public."ClassJobCategory" SET name_cn = '吟游诗人 机工士 舞者', name_en = 'BRD MCH DNC', name_jp = '吟遊詩人 機工士 踊り子' WHERE id = 171;
UPDATE public."ClassJobCategory" SET name_cn = '白魔法师 黑魔法师 召唤师 学者 占星术士 赤魔法师 贤者', name_en = 'WHM BLM SMN SCH AST RDM SGE', name_jp = '白魔道士 黒魔道士 召喚士 学者 占星術師 赤魔道士 賢者' WHERE id = 172;
UPDATE public."ClassJobCategory" SET name_cn = '骑士 武僧 战士 龙骑士 吟游诗人 白魔法师 黑魔法师 召唤师 学者 机工士 暗黑骑士 占星术士 武士 赤魔法师 绝枪战士 舞者 钐镰客 贤者', name_en = 'PLD MNK WAR DRG BRD WHM BLM SMN SCH MCH DRK AST SAM RDM GNB DNC RPR SGE', name_jp = 'ナイト モンク 戦士 竜騎士 吟遊詩人 白魔道士 黒魔道士 召喚士 学者 機工士 暗黒騎士 占星術師 侍 赤魔道士 ガンブレイカー 踊り子 リーパー 賢者' WHERE id = 173;
UPDATE public."ClassJobCategory" SET name_cn = '骑士 武僧 战士 龙骑士 吟游诗人 忍者 机工士 暗黑骑士 武士 绝枪战士 舞者 钐镰客', name_en = 'PLD MNK WAR DRG BRD NIN MCH DRK SAM GNB DNC RPR', name_jp = 'ナイト モンク 戦士 竜騎士 吟遊詩人 忍者 機工士 暗黒騎士 侍 ガンブレイカー 踊り子 リーパー' WHERE id = 174;
UPDATE public."ClassJobCategory" SET name_cn = '黑魔法师 召唤师 赤魔法师', name_en = 'BLM SMN RDM', name_jp = '黒魔道士 召喚士 赤魔道士' WHERE id = 175;
UPDATE public."ClassJobCategory" SET name_cn = '武僧 龙骑士 忍者 武士 钐镰客', name_en = 'MNK DRG NIN SAM RPR', name_jp = 'モンク 竜騎士 忍者 侍 リーパー' WHERE id = 176;
UPDATE public."ClassJobCategory" SET name_cn = '武僧 龙骑士 吟游诗人 忍者 机工士 武士 舞者 钐镰客', name_en = 'MNK DRG BRD NIN MCH SAM DNC RPR', name_jp = 'モンク 竜騎士 吟遊詩人 忍者 機工士 侍 踊り子 リーパー' WHERE id = 177;
UPDATE public."ClassJobCategory" SET name_cn = 'ナイト 戦士 黒魔道士 召喚士 暗黒騎士 赤魔道士 ガンブレイカー', name_en = 'PLD WAR BLM SMN DRK RDM GNB', name_jp = 'ナイト 戦士 黒魔道士 召喚士 暗黒騎士 赤魔道士 ガンブレイカー' WHERE id = 178;
UPDATE public."ClassJobCategory" SET name_cn = '白魔法师 召唤师 学者 占星术士 赤魔法师 贤者', name_en = 'WHM SMN SCH AST RDM SGE', name_jp = '白魔道士 召喚士 学者 占星術師 赤魔道士 賢者' WHERE id = 179;
UPDATE public."ClassJobCategory" SET name_cn = '钐镰客', name_en = 'RPR', name_jp = 'リーパー' WHERE id = 180;
UPDATE public."ClassJobCategory" SET name_cn = '贤者', name_en = 'SGE', name_jp = '賢者' WHERE id = 181;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 182;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 183;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 184;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 185;
UPDATE public."ClassJobCategory" SET name_cn = '防护职业（设限特职除外）', name_en = 'Tank (excluding limited jobs)', name_jp = 'TANKジョブ(リミテッドジョブを除く)' WHERE id = 186;
UPDATE public."ClassJobCategory" SET name_cn = '治疗职业（设限特职除外）', name_en = 'Healer (excluding limited jobs)', name_jp = 'HEALERジョブ(リミテッドジョブを除く)' WHERE id = 187;
UPDATE public."ClassJobCategory" SET name_cn = '近战职业（设限特职除外）', name_en = 'Melee DPS (excluding limited jobs)', name_jp = '近接物理DPSジョブ(リミテッドジョブを除く)' WHERE id = 188;
UPDATE public."ClassJobCategory" SET name_cn = '远程物理进攻职业（设限特职除外）', name_en = 'Physical Ranged DPS (excluding limited jobs)', name_jp = '遠隔物理DPSジョブ(リミテッドジョブを除く)' WHERE id = 189;
UPDATE public."ClassJobCategory" SET name_cn = '远程魔法进攻职业（设限特职除外）', name_en = 'Magical Ranged DPS (excluding limited jobs)', name_jp = '遠隔魔法DPSジョブ(リミテッドジョブを除く)' WHERE id = 190;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 191;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 192;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 193;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 194;
UPDATE public."ClassJobCategory" SET name_cn = null, name_en = null, name_jp = null WHERE id = 195;
