INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (0, '无效分类', 'Sephiroth Missions', '無効カテゴリ');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (1, '重生之境主线任务', 'Seventh Umbral Era Main Scenario Quests', 'メインクエスト：新生エオルゼア');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (2, '第七星历主线任务', 'Seventh Astral Era Main Scenario Quests', 'メインクエスト：第七星暦ストーリー');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (3, '苍穹之禁城主线任务', 'Heavensward Main Scenario Quests', 'メインクエスト：蒼天のイシュガルド');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (4, '龙诗战争终章主线任务', 'Dragonsong Main Scenario Quests', 'メインクエスト：竜詩戦争 完結編');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (5, '龙诗战争尾声主线任务', 'Post-Dragonsong Main Scenario Quests', 'メインクエスト：竜詩戦争 戦後編');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (6, '红莲之狂潮主线任务', 'Stormblood Main Scenario Quests', 'メインクエスト：紅蓮のリベレーター');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (7, '解放战争战后主线任务', 'Post-Stormblood Main Scenario Quests', 'メインクエスト：解放戦争 戦後編');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (8, '暗影之逆焰主线任务', 'Shadowbringers Main Scenario Quests', 'メインクエスト：漆黒のヴィランズ');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (9, '拂晓回归主线任务', 'Post-Shadowbringers Main Scenario Quests', 'メインクエスト：暁の帰還編');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (10, '末日序曲主线任务', 'Post-Shadowbringers Main Scenario Quests II', 'メインクエスト：終末の序曲編');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (11, '晓月之终途主线任务', 'Endwalker Main Scenario Quests', 'メインクエスト：暁月のフィナーレ');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (12, '崭新的冒险主线任务', 'Post-Endwalker Main Scenario Quests', 'メインクエスト：新たなる冒険編');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (13, '第七星历编年史：蛮神', 'Chronicles of a New Era - Primals', 'クロニクルクエスト：蛮神の脅威');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (14, '第七星历编年史：巴哈姆特', 'Chronicles of a New Era - Bahamut', 'クロニクルクエスト：バハムート');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (15, '第七星历编年史：水晶塔', 'Chronicles of a New Era - The Crystal Tower', 'クロニクルクエスト：クリスタルタワー');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (16, '第七星历编年史：亚历山大', 'Chronicles of a New Era - Alexander', 'クロニクルクエスト：アレキサンダー');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (17, '第七星历编年史：上古众神', 'Chronicles of a New Era - The Warring Triad', 'クロニクルクエスト：古の神々');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (18, '第七星历编年史：玛哈之影', 'Chronicles of a New Era - The Shadow of Mhach', 'クロニクルクエスト：シャドウ・オブ・マハ');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (19, '第七星历编年史：欧米茄', 'Chronicles of a New Era - Omega', 'クロニクルクエスト：オメガ');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (20, '第七星历编年史：重返伊瓦利斯', 'Chronicles of a New Era - Return to Ivalice', 'クロニクルクエスト：リターン・トゥ・イヴァリース');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (21, '第七星历编年史：四圣兽奇谭', 'Chronicles of a New Era - The Four Lords', 'クロニクルクエスト：四聖獣奇譚');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (22, '第七星历编年史：伊甸', 'Chronicles of a New Era - Eden', 'クロニクルクエスト：エデン');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (23, '寄叶异闻：暗黑天启', 'YoRHa: Dark Apocalypse', 'YoRHa: Dark Apocalypse');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (24, '第七星历编年史：维尔利特战役', 'Chronicles of a New Era - The Sorrow of Werlyt', 'クロニクルクエスト：ウェルリト戦役');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (25, '第七星历编年史：万魔殿', 'Chronicles of a New Era - Pandæmonium', 'クロニクルクエスト：パンデモニウム');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (26, '第七星历编年史：艾欧泽亚神话', 'Chronicles of a New Era - Myths of the Realm', 'クロニクルクエスト：ミソロジー・オブ・エオルゼア');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (27, null, '友好部族クエスト：オミクロン族', '友好部族クエスト：オミクロン族');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (28, '悌阳象族任务', 'Arkasodara Quests', '友好部族クエスト：アルカソーダラ族');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (29, '蜥蜴人族任务', 'Amalj''aa Quests', '友好部族クエスト：アマルジャ族');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (30, '妖精族任务', 'Sylph Quests', '友好部族クエスト：シルフ族');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (31, '地灵族任务', 'Kobold Quests', '友好部族クエスト：コボルド族');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (32, '鱼人族任务', 'Sahagin Quests', '友好部族クエスト：サハギン族');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (33, '鸟人族任务', 'Ixal Quests', '友好部族クエスト：イクサル族');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (34, '瓦努族任务', 'Vanu Vanu Quests', '友好部族クエスト：バヌバヌ族');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (35, '骨颌族任务', 'Vath Quests', '友好部族クエスト：グナース族');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (36, '莫古力族任务', 'Moogle Quests', '友好部族クエスト：モーグリ族');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (37, '甲人族任务', 'Kojin Quests', '友好部族クエスト：コウジン族');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (38, '阿难陀族任务', 'Ananta Quests', '友好部族クエスト：アナンタ族');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (39, '鲶鱼精族任务', 'Namazu Quests', '友好部族クエスト：ナマズオ族');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (40, '仙子族任务', 'Pixie Quests', '友好部族クエスト：ピクシー族');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (41, '奇塔利族任务', 'Qitari Quests', '友好部族クエスト：キタリ族');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (42, '矮人族任务', 'Dwarf Quests', '友好部族クエスト：ドワーフ族');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (43, '支线剧情任务', 'Side Story Quests', 'サブストーリークエスト');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (44, '拉诺西亚支线任务', 'Lominsan Sidequests', 'サブクエスト：ラノシア');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (45, '黑衣森林支线任务', 'Gridanian Sidequests', 'サブクエスト：黒衣森');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (46, '萨纳兰支线任务', 'Ul''dahn Sidequests', 'サブクエスト：ザナラーン');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (47, '库尔札斯支线任务', 'Coerthan Sidequests', 'サブクエスト：クルザス');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (48, '摩杜纳支线任务', 'Mor Dhonan Sidequests', 'サブクエスト：モードゥナ');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (49, '伊修加德支线任务', 'Ishgardian Sidequests', 'サブクエスト：イシュガルド');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (50, '阿巴拉提亚支线任务', 'Abalathian Sidequests', 'サブクエスト：アバラシア');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (51, '龙堡支线任务', 'Dravanian Sidequests', 'サブクエスト：ドラヴァニア');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (52, '魔大陆支线任务', 'Azys Lla Sidequests', 'サブクエスト：アジス・ラー');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (53, '基拉巴尼亚支线任务', 'Gyr Abanian Sidequests', 'サブクエスト：ギラバニア');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (54, '奥萨德支线任务', 'Othardian Sidequests', 'サブクエスト：オサード');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (55, '远东之国支线任务', 'Hingan Sidequests', 'サブクエスト：ひんがしの国');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (56, '雷克兰德支线任务', 'Lakeland Sidequests', 'サブクエスト：レイクランド');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (57, '珂露西亚岛支线任务', 'Kholusian Sidequests', 'サブクエスト：コルシア島');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (58, '安穆·艾兰支线任务', 'Amh Araeng Sidequests', 'サブクエスト：アム・アレーン');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (59, '伊尔美格支线任务', 'Il Mheg Sidequests', 'サブクエスト：イル・メグ');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (60, '拉凯提卡大森林支线任务', 'Rak''tika Sidequests', 'サブクエスト：ラケティカ大森林');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (61, '黑风海支线任务', 'Tempest Sidequests', 'サブクエスト：テンペスト');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (62, '萨雷安支线任务', 'Sharlayan Sidequests', 'サブクエスト：シャーレアン');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (63, '萨维奈岛支线任务', 'Thavnairian Sidequests', 'サブクエスト：サベネア島');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (64, '加雷马支线任务', 'Garlean Sidequests', 'サブクエスト：ガレマルド');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (65, '叹息海支线任务', 'Mare Lamentorum Sidequests', 'サブクエスト：嘆きの海');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (66, '厄尔庇斯支线任务', 'Elpis Sidequests', 'サブクエスト：エルピス');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (67, '天外天垓支线任务', 'Ultima Thule Sidequests', 'サブクエスト：ウルティマ・トゥーレ');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (68, '战斗精英职业任务', 'Disciple of War Quests', 'クラスクエスト：ファイター');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (69, '魔法导师职业任务', 'Disciple of Magic Quests', 'クラスクエスト：ソーサラー');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (70, '能工巧匠职业任务', 'Disciple of the Hand Quests', 'クラスクエスト：クラフター');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (71, '大地使者职业任务', 'Disciple of the Land Quests', 'クラスクエスト：ギャザラー');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (72, '中庸工艺馆交易职业任务', 'Crystalline Mean Quests', 'クラスクエスト：ミーン工芸館取引');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (73, '萨雷安魔法大学交易职业任务', 'Studium Quests', 'クラスクエスト：魔法大学取引');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (74, '战斗精英特职任务', 'Disciple of War Job Quests', 'ジョブクエスト：ファイター');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (75, '魔法导师特职任务', 'Disciple of Magic Job Quests', 'ジョブクエスト：ソーサラー');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (76, '职能任务', 'Role Quests', 'ロールクエスト');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (77, '军队任务', 'Grand Company Quests', 'グランドカンパニークエスト');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (78, '季节活动', 'Seasonal Events', 'シーズナルイベント');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (79, '其他任务', 'Special Quests', 'エトセトラクエスト');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (80, '佣兵理符', 'Battlecraft Leves', 'リーヴ：傭兵稼業');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (81, '采矿理符', 'Mining Leves', 'リーヴ：採掘師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (82, '园艺理符', 'Botany Leves', 'リーヴ：園芸師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (83, '钓鱼理符', 'Fishing Leves', 'リーヴ：漁師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (84, '木工理符', 'Carpentry Leves', 'リーヴ：木工師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (85, '锻冶理符', 'Blacksmithing Leves', 'リーヴ：鍛冶師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (86, '铸甲理符', 'Armoring Leves', 'リーヴ：甲冑師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (87, '雕金理符', 'Goldsmithing Leves', 'リーヴ：彫金師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (88, '制革理符', 'Leatherworking Leves', 'リーヴ：革細工師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (89, '裁缝理符', 'Clothcrafting Leves', 'リーヴ：裁縫師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (90, '炼金理符', 'Alchemy Leves', 'リーヴ：錬金術師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (91, '烹调理符', 'Cooking Leves', 'リーヴ：調理師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (92, '神殿骑士团佣兵理符', 'Ishgardian Battlecraft Leves', '神殿騎士団リーヴ：傭兵稼業');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (93, '神殿骑士团采矿理符', 'Ishgardian Mining Leves', '神殿騎士団リーヴ：採掘師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (94, '神殿骑士团园艺理符', 'Ishgardian Botany Leves', '神殿騎士団リーヴ：園芸師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (95, '神殿骑士团钓鱼理符', 'Ishgardian Fishing Leves', '神殿騎士団リーヴ：漁師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (96, '神殿骑士团木工理符', 'Ishgardian Carpentry Leves', '神殿騎士団リーヴ：木工師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (97, '神殿骑士团锻冶理符', 'Ishgardian Blacksmithing Leves', '神殿騎士団リーヴ：鍛冶師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (98, '神殿骑士团铸甲理符', 'Ishgardian Armoring Leves', '神殿騎士団リーヴ：甲冑師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (99, '神殿骑士团雕金理符', 'Ishgardian Goldsmithing Leves', '神殿騎士団リーヴ：彫金師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (100, '神殿骑士团制革理符', 'Ishgardian Leatherworking Leves', '神殿騎士団リーヴ：革細工師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (101, '神殿骑士团裁缝理符', 'Ishgardian Clothcrafting Leves', '神殿騎士団リーヴ：裁縫師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (102, '神殿骑士团炼金理符', 'Ishgardian Alchemy Leves', '神殿騎士団リーヴ：錬金術師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (103, '神殿骑士团烹调理符', 'Ishgardian Cooking Leves', '神殿騎士団リーヴ：調理師');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (104, '特殊部队理符', 'Faction Leves', 'ギルドリーヴ：ファクション');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (105, '军队理符', 'Company Leves', 'グランドカンパニーリーヴ');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (106, '迷宫挑战', 'Instanced Dungeons', 'コンテンツ：ダンジョン');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (107, '大型任务', 'Instanced Raids', 'コンテンツ：レイド');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (108, '讨伐歼灭战', 'Instanced Battles', 'コンテンツ：討伐・討滅戦');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (109, '其他任务', 'Other Duties', 'コンテンツ：その他');
INSERT INTO public."JournalCategory" (id, name_cn, name_en, name_jp) VALUES (110, '遗产任务', 'Legacy Quests', 'レガシークエスト');
