INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (0, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (1, '重生之境', 'Seventh Umbral Era', '新生エオルゼア');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (2, '第七星历', 'Seventh Astral Era', '第七星暦ストーリー');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (3, '苍穹之禁城', 'Heavensward', '蒼天のイシュガルド');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (4, '龙诗战争终章', 'Dragonsong War', '竜詩戦争 完結編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (5, '龙诗战争尾声', 'Post-Dragonsong War', '竜詩戦争 戦後編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (6, '红莲之狂潮', 'Stormblood', '紅蓮のリベレーター');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (7, '解放战争战后', 'Post-Ala Mhigan Liberation', '解放戦争 戦後編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (8, '暗影之逆焰', 'Shadowbringers', '漆黒のヴィランズ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (9, '拂晓回归', 'The Voyage Home', '暁の帰還編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (10, '末日序曲', 'Dark Reprise', '終末の序曲編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (11, '晓月之终途', 'Endwalker', '暁月のフィナーレ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (12, '崭新的冒险', 'Newfound Adventure', '新たなる冒険編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (13, '蛮神威胁', 'Primal Quests', '蛮神の脅威');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (14, '巴哈姆特', 'Bahamut Quests', 'バハムート');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (15, '水晶塔', 'Crystal Tower Quests', 'クリスタルタワー');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (16, '亚历山大', 'Alexander Quests', 'アレキサンダー');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (17, '上古众神', 'Heavensward Primal Quests', '古の神々');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (18, '玛哈之影', 'Shadow of Mhach Quests', 'シャドウ・オブ・マハ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (19, '欧米茄时空狭缝', 'Omega Quests', '次元の狭間オメガ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (20, null, 'Omega: Beyond the Rift', '次元の狭間オメガ 番外編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (21, '重返伊瓦利斯', 'Return to Ivalice', 'リターン・トゥ・イヴァリース');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (22, '四圣兽奇谭', 'The Four Lords', '四聖獣奇譚');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (23, '伊甸', 'Eden', 'エデン');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (24, '寄叶异闻：暗黑天启', 'YoRHa: Dark Apocalypse', 'YoRHa: Dark Apocalypse');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (25, '神兵系列', 'Garlemald''s Machinations', 'ウェポンシリーズ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (26, '万魔殿', 'Pandæmonium', 'パンデモニウム');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (27, '艾欧泽亚神话', 'Myths of the Realm', 'ミソロジー・オブ・エオルゼア');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (28, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (29, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (30, '剧情任务', 'Main Quests', 'ストーリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (31, '日常任务', 'Daily Quests', 'デイリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (32, '剧情任务', 'Main Quests', 'ストーリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (33, '日常任务', 'Daily Quests', 'デイリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (34, '剧情任务', 'Main Quests', 'ストーリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (35, '日常任务', 'Daily Quests', 'デイリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (36, '剧情任务', 'Main Quests', 'ストーリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (37, '日常任务', 'Daily Quests', 'デイリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (38, '剧情任务', 'Main Quests', 'ストーリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (39, '日常任务', 'Daily Quests', 'デイリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (40, '剧情任务', 'Main Quests', 'ストーリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (41, '日常任务', 'Daily Quests', 'デイリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (42, '剧情任务', 'Main Quests', 'ストーリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (43, '日常任务', 'Daily Quests', 'デイリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (44, '剧情任务', 'Main Quests', 'ストーリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (45, '日常任务', 'Daily Quests', 'デイリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (46, '剧情任务', 'Main Quests', 'ストーリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (47, '日常任务', 'Daily Quests', 'デイリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (48, '剧情任务', 'Main Quests', 'ストーリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (49, '日常任务', 'Daily Quests', 'デイリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (50, '剧情任务', 'Main Quests', 'ストーリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (51, '日常任务', 'Daily Quests', 'デイリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (52, '剧情任务', 'Main Quests', 'ストーリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (53, '日常任务', 'Daily Quests', 'デイリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (54, '剧情任务', 'Main Quests', 'ストーリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (55, '日常任务', 'Daily Quests', 'デイリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (56, '剧情任务', 'Main Quests', 'ストーリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (57, '日常任务', 'Daily Quests', 'デイリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (58, '剧情任务', 'Main Quests', 'ストーリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (59, '日常任务', 'Daily Quests', 'デイリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (60, '龙诗战争外传', 'Tales of the Dragonsong War', '竜詩戦争 番外編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (61, '拂晓回归外传', 'Tales from the Shadows', '暁の帰還 番外編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (62, null, 'Tales of Newfound Adventure', '新たなる冒険 番外編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (63, '非著名调查员', 'Hildibrand Quests', 'ヒルディブランド');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (64, '非著名调查员：苍穹之章', 'Further Hildibrand Adventures', 'ヒルディブランド 蒼天編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (65, '非著名调查员：红莲之章', 'Even Further Hildibrand Adventures', 'ヒルディブランド 紅蓮編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (66, '希尔迪布兰德归来', 'Somehow Further Hildibrand Adventures', '帰ってきたヒルディブランド');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (67, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (68, '黄道武器', 'Zodiac Weapons', 'ゾディアックウェポン');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (69, '元灵武器', 'Anima Weapons', 'アニマウェポン');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (70, '禁地优雷卡', 'The Forbidden Land, Eureka', '禁断の地 エウレカ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (71, '天佑女王', 'Resistance Weapons', 'セイブ・ザ・クイーン');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (72, '邮差莫古力', 'Delivery Moogle Quests', 'レターモーグリ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (73, '圣恩达利姆神学院记', 'Scholasticate Quests', '聖アンダリム神学院記');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (74, '虚无界再生计划', 'Void Quests', 'ヴォイド再生計画');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (75, '塔塔露的大繁荣商店', 'Tataru''s Grand Endeavor', 'タタルの大繁盛商店');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (76, '多玛冒险者团', 'Doman Adventurers'' Guild Quests', 'ドマ冒険者団');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (77, '多玛飞地重建记', 'Doman Reconstruction Quests', 'ドマ町人地復興記');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (78, '重建伊修加德：剧情任务', 'Ishgardian Restoration Main Quests', 'イシュガルド復興：ストーリークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (79, '重建伊修加德：支线任务', 'Ishgardian Restoration Sidequests', 'イシュガルド復興：サブクエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (80, null, 'Island Sanctuary Quests', '無人島開拓記');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (81, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (82, '蛮族盟友', 'Allied Tribal Quests', '友好部族エクストラストーリー');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (83, '蛮族盟友：苍穹之章', 'Heavensward Tribal Quests', '友好部族エクストラストーリー 蒼天編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (84, '蛮族盟友：红莲之章', 'Stormblood Tribal Quests', '友好部族エクストラストーリー 紅蓮編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (85, '异国的诗人', 'Wandering Minstrel Quests', '異邦の詩人');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (86, '支线任务：拉诺西亚', 'La Noscean Sidequests', 'サブクエスト：ラノシア');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (87, '支线任务：黑衣森林', 'Gridanian Sidequests', 'サブクエスト：黒衣森');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (88, '支线任务：萨纳兰', 'Ul''dahn Sidequests', 'サブクエスト：ザナラーン');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (89, '支线任务：库尔札斯', 'Coerthan Sidequests', 'サブクエスト：クルザス');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (90, '支线任务：摩杜纳', 'Mor Dhonan Sidequests', 'サブクエスト：モードゥナ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (91, '支线任务：伊修加德', 'Ishgardian Sidequests', 'サブクエスト：イシュガルド');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (92, '支线任务：阿巴拉提亚云海', 'Abalathian Sidequests', 'サブクエスト：アバラシア雲海');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (93, '支线任务：龙堡参天高地', 'Dravanian Forelands Sidequests', 'サブクエスト：高地ドラヴァニア');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (94, '支线任务：龙堡内陆低地', 'Dravanian Hinterlands Sidequests', 'サブクエスト：低地ドラヴァニア');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (95, '支线任务：翻云雾海', 'Churning Mists Sidequests', 'サブクエスト：ドラヴァニア雲海');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (96, '支线任务：田园郡', 'Idyllshire Sidequests', 'サブクエスト：イディルシャイア');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (97, '支线任务：魔大陆', 'Azys Lla Sidequests', 'サブクエスト：アジス・ラー');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (98, '支线任务：神拳痕', 'Rhalgr''s Reach Sidequests', 'サブクエスト：ラールガーズリーチ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (99, '支线任务：基拉巴尼亚边区', 'Fringes Sidequests', 'サブクエスト：ギラバニア辺境地帯');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (100, '支线任务：基拉巴尼亚山区', 'Peaks Sidequests', 'サブクエスト：ギラバニア山岳地帯');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (101, '支线任务：基拉巴尼亚湖区', 'Lochs Sidequests', 'サブクエスト：ギラバニア湖畔地帯');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (102, '支线任务：黄金港', 'Kugane Sidequests', 'サブクエスト：クガネ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (103, '支线任务：红玉海', 'Ruby Sea Sidequests', 'サブクエスト：紅玉海');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (104, '支线任务：延夏', 'Yanxia Sidequests', 'サブクエスト：ヤンサ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (105, '支线任务：太阳神草原', 'Azim Steppe Sidequests', 'サブクエスト：アジムステップ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (106, '支线任务：水晶都', 'Crystarium Sidequests', 'サブクエスト：クリスタリウム');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (107, '支线任务：游末邦', 'Eulmore Sidequests', 'サブクエスト：ユールモア');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (108, '支线任务：雷克兰德', 'Lakeland Sidequests', 'サブクエスト：レイクランド');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (109, '支线任务：珂露西亚岛', 'Kholusia Sidequests', 'サブクエスト：コルシア島');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (110, '支线任务：安穆·艾兰', 'Amh Araeng Sidequests', 'サブクエスト：アム・アレーン');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (111, '支线任务：伊尔美格', 'Il Mheg Sidequests', 'サブクエスト：イル・メグ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (112, '支线任务：拉凯提卡大森林', 'Rak''tika Sidequests', 'サブクエスト：ラケティカ大森林');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (113, '支线任务：黑风海', 'Tempest Sidequests', 'サブクエスト：テンペスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (114, '支线任务：旧萨雷安', 'Old Sharlayan Sidequests', 'サブクエスト：オールド・シャーレアン');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (115, '支线任务：拉札罕', 'Radz-at-Han Sidequests', 'サブクエスト：ラザハン');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (116, '支线任务：迷津', 'Labyrinthos Sidequests', 'サブクエスト：ラヴィリンソス');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (117, '支线任务：萨维奈岛', 'Thavnairian Sidequests', 'サブクエスト：サベネア島');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (118, '支线任务：加雷马', 'Garlean Sidequests', 'サブクエスト：ガレマルド');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (119, '支线任务：叹息海', 'Mare Lamentorum Sidequests', 'サブクエスト：嘆きの海');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (120, '支线任务：厄尔庇斯', 'Elpis Sidequests', 'サブクエスト：エルピス');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (121, '支线任务：天外天垓', 'Ultima Thule Sidequests', 'サブクエスト：ウルティマ・トゥーレ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (122, '剑术师任务', 'Gladiator Quests', '剣術士クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (123, '格斗家任务', 'Pugilist Quests', '格闘士クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (124, '斧术师任务', 'Marauder Quests', '斧術士クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (125, '枪术师任务', 'Lancer Quests', '槍術士クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (126, '弓箭手任务', 'Archer Quests', '弓術士クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (127, '双剑师任务', 'Rogue Quests', '双剣士クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (128, '幻术师任务', 'Conjurer Quests', '幻術士クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (129, '咒术师任务', 'Thaumaturge Quests', '呪術士クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (130, '秘术师任务', 'Arcanist Quests', '巴術士クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (131, '刻木匠任务', 'Carpenter Quests', '木工師クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (132, '锻铁匠任务', 'Blacksmith Quests', '鍛冶師クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (133, '铸甲匠任务', 'Armorer Quests', '甲冑師クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (134, '雕金匠任务', 'Goldsmith Quests', '彫金師クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (135, '制革匠任务', 'Leatherworker Quests', '革細工師クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (136, '裁衣匠任务', 'Weaver Quests', '裁縫師クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (137, '炼金术士任务', 'Alchemist Quests', '錬金術師クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (138, '烹调师任务', 'Culinarian Quests', '調理師クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (139, '采矿工任务', 'Miner Quests', '採掘師クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (140, '园艺工任务', 'Botanist Quests', '園芸師クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (141, '捕鱼人任务', 'Fisher Quests', '漁師クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (142, '骑士任务', 'Paladin Quests', 'ナイトクエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (143, '武僧任务', 'Monk Quests', 'モンククエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (144, '战士任务', 'Warrior Quests', '戦士クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (145, '龙骑士任务', 'Dragoon Quests', '竜騎士クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (146, '吟游诗人任务', 'Bard Quests', '吟遊詩人クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (147, '忍者任务', 'Ninja Quests', '忍者クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (148, '白魔法师任务', 'White Mage Quests', '白魔道士クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (149, '黑魔法师任务', 'Black Mage Quests', '黒魔道士クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (150, '召唤师任务', 'Summoner Quests', '召喚士クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (151, '学者任务', 'Scholar Quests', '学者クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (152, '暗黑骑士任务', 'Dark Knight Quests', '暗黒騎士クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (153, '机工士任务', 'Machinist Quests', '機工士クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (154, '占星术士任务', 'Astrologian Quests', '占星術師クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (155, '武士任务', 'Samurai Quests', '侍クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (156, '赤魔法师任务', 'Red Mage Quests', '赤魔道士クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (157, '绝枪战士任务', 'Gunbreaker Quests', 'ガンブレイカークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (158, '舞者任务', 'Dancer Quests', '踊り子クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (159, '贤者任务', 'Sage Quests', '賢者クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (160, '钐镰客任务', 'Reaper Quests', 'リーパークエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (161, '青魔法师任务', 'Blue Mage Quests', '青魔道士クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (162, '金属工艺部任务', 'Facet of Forging Quests', '錬鉄科クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (163, '手工工艺部任务', 'Facet of Crafting Quests', '手工科クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (164, '食药工艺部任务', 'Facet of Nourishing Quests', '食薬科クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (165, '大地资源部任务', 'Facet of Gathering Quests', '調達科クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (166, '水生资源部任务', 'Facet of Fishing Quests', '漁業科クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (167, '中庸工艺馆剧情任务', 'Crystalline Mean Quests', 'ミーン工芸館エクストラストーリー');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (168, '考古系任务', 'Faculty of Archaeology Quests', '考古学部クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (169, '天文系任务', 'Faculty of Astronomy Quests', '天文学部クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (170, '医学系任务', 'Faculty of Medicine Quests', '医学部クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (171, '文化系任务', 'Faculty of Anthropology Quests', '文化学部クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (172, '以太系任务', 'Faculty of Aetherology Quests', 'エーテル学部クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (173, '萨雷安魔法大学剧情任务', 'Studium Quests', '魔法大学エクストラストーリー');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (174, '防护职能任务', 'Tank Role Quests (Shadowbringers)', 'TANKロールクエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (175, '治疗职能任务', 'Healer Role Quests (Shadowbringers)', 'HEALERロールクエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (176, '物理进攻职能任务', 'Physical DPS Role Quests (Shadowbringers)', 'ファイター系DPSロールクエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (177, '魔法进攻职能任务', 'Magical Ranged DPS Role Quests (Shadowbringers)', 'ソーサラー系DPSロールクエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (178, '职能剧情任务', 'Role Quests (Shadowbringers)', 'ロールエクストラストーリー');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (179, '防护职能任务：晓月之章', 'Tank Role Quests (Endwalker)', 'TANKロールクエスト 暁月編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (180, '治疗职能任务：晓月之章', 'Healer Role Quests (Endwalker)', 'HEALERロールクエスト 暁月編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (181, '近战职能任务：晓月之章', 'Melee DPS Role Quests (Endwalker)', '近接物理DPSロールクエスト 暁月編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (182, '远程物理职能任务：晓月之章', 'Physical Ranged DPS Role Quests (Endwalker)', '遠隔物理DPSロールクエスト 暁月編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (183, '远程魔法职能任务：晓月之章', 'Magical Ranged DPS Role Quests (Endwalker)', '遠隔魔法DPSロールクエスト 暁月編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (184, '职能剧情任务：晓月之章', 'Role Quests (Endwalker)', 'ロールエクストラストーリー 暁月編');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (185, '黑涡团任务', 'Maelstrom Quests', '黒渦団クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (186, '双蛇党任务', 'Order of the Twin Adder Quests', '双蛇党クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (187, '恒辉队任务', 'Immortal Flames Quests', '不滅隊クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (188, '季节活动', 'Seasonal Events', 'シーズナルクエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (189, '降神节', 'Heavensturn Events', '降神祭');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (190, '东节', 'Eastern Duties', 'CHS／KO専用');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (191, '恋人节', 'Valentione''s Day Events', 'ヴァレンティオンデー');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (192, '恋人节&女儿节', 'Valentione''s & Little Ladies'' Day Events', 'ヴァレンティオン＆プリンセスデー');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (193, '女儿节', 'Little Ladies'' Day Events', 'プリンセスデー');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (194, '彩蛋狩猎', 'Egg Hunts', 'エッグハント');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (195, '金碟嘉年华', 'Gold Saucer Festivities', 'ゴールドソーサー・フェスティバル');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (196, '红莲节', 'Moonfire Faire Events', '紅蓮祭');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (197, '新生庆典', 'Rising Events', '新生祭');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (198, '守护天节', 'All Saints'' Wake Events', '守護天節');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (199, '星芒节', 'Starlight Celebration Events', '星芒祭');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (200, '其他季节活动', 'Other Seasonal Events', 'その他シーズナルイベント');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (201, '纪念任务', 'Special Quests', 'スペシャルクエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (202, '来访者任务', 'Collaboration Quests', '来訪者クエスト');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (203, '佣兵理符任务', 'Battlecraft Levequests', '傭兵リーヴ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (204, '刻木匠理符任务', 'Carpenter Levequests', '木工師リーヴ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (205, '锻铁匠理符任务', 'Blacksmith Levequests', '鍛冶師リーヴ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (206, '铸甲匠理符任务', 'Armorer Levequests', '甲冑師リーヴ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (207, '雕金匠理符任务', 'Goldsmith Levequests', '彫金師リーヴ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (208, '制革匠理符任务', 'Leatherworker Levequests', '革細工師リーヴ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (209, '裁衣匠理符任务', 'Weaver Levequests', '裁縫師リーヴ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (210, '炼金术士理符任务', 'Alchemist Levequests', '錬金術師リーヴ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (211, '烹调师理符任务', 'Culinarian Levequests', '調理師リーヴ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (212, '采矿工理符任务', 'Miner Levequests', '採掘師リーヴ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (213, '园艺工理符任务', 'Botanist Levequests', '園芸師リーヴ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (214, '捕鱼人理符任务', 'Fisher Levequests', '漁師リーヴ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (215, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (216, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (217, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (218, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (219, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (220, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (221, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (222, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (223, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (224, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (225, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (226, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (227, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (228, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (229, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (230, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (231, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (232, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (233, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (234, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (235, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (236, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (237, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (238, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (239, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (240, '黑涡团理符任务', 'Maelstrom Levequests', '黒渦団リーヴ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (241, '双蛇党理符任务', 'Order of the Twin Adder Levequests', '双蛇党リーヴ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (242, '恒辉队理符任务', 'Immortal Flames Levequests', '不滅隊リーヴ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (243, '迷宫挑战', 'Instanced Dungeons', 'ダンジョン');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (244, '大型任务', 'Instanced Raids', 'レイド');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (245, '讨伐歼灭战', 'Trials', '討伐・討滅戦');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (246, '深层迷宫', 'Deep Dungeons', 'ディープダンジョン');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (247, '禁地优雷卡', 'Eureka Expedition Quests', '禁断の地 エウレカ');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (248, '天佑女王', 'Save the Queen: Blades of Gunnhildr', 'セイブ・ザ・クイーン');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (249, null, null, null);
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (250, '行会令', 'Guildhests', 'ギルドオーダー');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (251, '主线剧情任务：第六星历', 'Legacy Main Scenario Quests', 'メインクエスト：レガシー');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (252, '支线任务：第六星历', 'Legacy Sidequests', 'サブクエスト：レガシー');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (253, '职业任务：第六星历', 'Legacy Class Quests', 'クラスクエスト：レガシー');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (254, '特职任务：第六星历', 'Legacy Job Quests', 'ジョブクエスト：レガシー');
INSERT INTO public."JournalGenre" (id, name_cn, name_en, name_jp) VALUES (255, '军队任务：第六星历', 'Legacy Grand Company Quests', 'グランドカンパニークエスト：レガシー');
