UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 0;
UPDATE public."JournalGenre" SET name_cn = '重生之境', name_en = 'Seventh Umbral Era', name_jp = '新生エオルゼア' WHERE id = 1;
UPDATE public."JournalGenre" SET name_cn = '第七星历', name_en = 'Seventh Astral Era', name_jp = '第七星暦ストーリー' WHERE id = 2;
UPDATE public."JournalGenre" SET name_cn = '苍穹之禁城', name_en = 'Heavensward', name_jp = '蒼天のイシュガルド' WHERE id = 3;
UPDATE public."JournalGenre" SET name_cn = '龙诗战争终章', name_en = 'Dragonsong War', name_jp = '竜詩戦争 完結編' WHERE id = 4;
UPDATE public."JournalGenre" SET name_cn = '龙诗战争尾声', name_en = 'Post-Dragonsong War', name_jp = '竜詩戦争 戦後編' WHERE id = 5;
UPDATE public."JournalGenre" SET name_cn = '红莲之狂潮', name_en = 'Stormblood', name_jp = '紅蓮のリベレーター' WHERE id = 6;
UPDATE public."JournalGenre" SET name_cn = '解放战争战后', name_en = 'Post-Ala Mhigan Liberation', name_jp = '解放戦争 戦後編' WHERE id = 7;
UPDATE public."JournalGenre" SET name_cn = '暗影之逆焰', name_en = 'Shadowbringers', name_jp = '漆黒のヴィランズ' WHERE id = 8;
UPDATE public."JournalGenre" SET name_cn = '拂晓回归', name_en = 'The Voyage Home', name_jp = '暁の帰還編' WHERE id = 9;
UPDATE public."JournalGenre" SET name_cn = '末日序曲', name_en = 'Dark Reprise', name_jp = '終末の序曲編' WHERE id = 10;
UPDATE public."JournalGenre" SET name_cn = '晓月之终途', name_en = 'Endwalker', name_jp = '暁月のフィナーレ' WHERE id = 11;
UPDATE public."JournalGenre" SET name_cn = '崭新的冒险', name_en = 'Newfound Adventure', name_jp = '新たなる冒険編' WHERE id = 12;
UPDATE public."JournalGenre" SET name_cn = '蛮神威胁', name_en = 'Primal Quests', name_jp = '蛮神の脅威' WHERE id = 13;
UPDATE public."JournalGenre" SET name_cn = '巴哈姆特', name_en = 'Bahamut Quests', name_jp = 'バハムート' WHERE id = 14;
UPDATE public."JournalGenre" SET name_cn = '水晶塔', name_en = 'Crystal Tower Quests', name_jp = 'クリスタルタワー' WHERE id = 15;
UPDATE public."JournalGenre" SET name_cn = '亚历山大', name_en = 'Alexander Quests', name_jp = 'アレキサンダー' WHERE id = 16;
UPDATE public."JournalGenre" SET name_cn = '上古众神', name_en = 'Heavensward Primal Quests', name_jp = '古の神々' WHERE id = 17;
UPDATE public."JournalGenre" SET name_cn = '玛哈之影', name_en = 'Shadow of Mhach Quests', name_jp = 'シャドウ・オブ・マハ' WHERE id = 18;
UPDATE public."JournalGenre" SET name_cn = '欧米茄时空狭缝', name_en = 'Omega Quests', name_jp = '次元の狭間オメガ' WHERE id = 19;
UPDATE public."JournalGenre" SET name_cn = null, name_en = 'Omega: Beyond the Rift', name_jp = '次元の狭間オメガ 番外編' WHERE id = 20;
UPDATE public."JournalGenre" SET name_cn = '重返伊瓦利斯', name_en = 'Return to Ivalice', name_jp = 'リターン・トゥ・イヴァリース' WHERE id = 21;
UPDATE public."JournalGenre" SET name_cn = '四圣兽奇谭', name_en = 'The Four Lords', name_jp = '四聖獣奇譚' WHERE id = 22;
UPDATE public."JournalGenre" SET name_cn = '伊甸', name_en = 'Eden', name_jp = 'エデン' WHERE id = 23;
UPDATE public."JournalGenre" SET name_cn = '寄叶异闻：暗黑天启', name_en = 'YoRHa: Dark Apocalypse', name_jp = 'YoRHa: Dark Apocalypse' WHERE id = 24;
UPDATE public."JournalGenre" SET name_cn = '神兵系列', name_en = 'Garlemald''s Machinations', name_jp = 'ウェポンシリーズ' WHERE id = 25;
UPDATE public."JournalGenre" SET name_cn = '万魔殿', name_en = 'Pandæmonium', name_jp = 'パンデモニウム' WHERE id = 26;
UPDATE public."JournalGenre" SET name_cn = '艾欧泽亚神话', name_en = 'Myths of the Realm', name_jp = 'ミソロジー・オブ・エオルゼア' WHERE id = 27;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 28;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 29;
UPDATE public."JournalGenre" SET name_cn = '剧情任务', name_en = 'Main Quests', name_jp = 'ストーリークエスト' WHERE id = 30;
UPDATE public."JournalGenre" SET name_cn = '日常任务', name_en = 'Daily Quests', name_jp = 'デイリークエスト' WHERE id = 31;
UPDATE public."JournalGenre" SET name_cn = '剧情任务', name_en = 'Main Quests', name_jp = 'ストーリークエスト' WHERE id = 32;
UPDATE public."JournalGenre" SET name_cn = '日常任务', name_en = 'Daily Quests', name_jp = 'デイリークエスト' WHERE id = 33;
UPDATE public."JournalGenre" SET name_cn = '剧情任务', name_en = 'Main Quests', name_jp = 'ストーリークエスト' WHERE id = 34;
UPDATE public."JournalGenre" SET name_cn = '日常任务', name_en = 'Daily Quests', name_jp = 'デイリークエスト' WHERE id = 35;
UPDATE public."JournalGenre" SET name_cn = '剧情任务', name_en = 'Main Quests', name_jp = 'ストーリークエスト' WHERE id = 36;
UPDATE public."JournalGenre" SET name_cn = '日常任务', name_en = 'Daily Quests', name_jp = 'デイリークエスト' WHERE id = 37;
UPDATE public."JournalGenre" SET name_cn = '剧情任务', name_en = 'Main Quests', name_jp = 'ストーリークエスト' WHERE id = 38;
UPDATE public."JournalGenre" SET name_cn = '日常任务', name_en = 'Daily Quests', name_jp = 'デイリークエスト' WHERE id = 39;
UPDATE public."JournalGenre" SET name_cn = '剧情任务', name_en = 'Main Quests', name_jp = 'ストーリークエスト' WHERE id = 40;
UPDATE public."JournalGenre" SET name_cn = '日常任务', name_en = 'Daily Quests', name_jp = 'デイリークエスト' WHERE id = 41;
UPDATE public."JournalGenre" SET name_cn = '剧情任务', name_en = 'Main Quests', name_jp = 'ストーリークエスト' WHERE id = 42;
UPDATE public."JournalGenre" SET name_cn = '日常任务', name_en = 'Daily Quests', name_jp = 'デイリークエスト' WHERE id = 43;
UPDATE public."JournalGenre" SET name_cn = '剧情任务', name_en = 'Main Quests', name_jp = 'ストーリークエスト' WHERE id = 44;
UPDATE public."JournalGenre" SET name_cn = '日常任务', name_en = 'Daily Quests', name_jp = 'デイリークエスト' WHERE id = 45;
UPDATE public."JournalGenre" SET name_cn = '剧情任务', name_en = 'Main Quests', name_jp = 'ストーリークエスト' WHERE id = 46;
UPDATE public."JournalGenre" SET name_cn = '日常任务', name_en = 'Daily Quests', name_jp = 'デイリークエスト' WHERE id = 47;
UPDATE public."JournalGenre" SET name_cn = '剧情任务', name_en = 'Main Quests', name_jp = 'ストーリークエスト' WHERE id = 48;
UPDATE public."JournalGenre" SET name_cn = '日常任务', name_en = 'Daily Quests', name_jp = 'デイリークエスト' WHERE id = 49;
UPDATE public."JournalGenre" SET name_cn = '剧情任务', name_en = 'Main Quests', name_jp = 'ストーリークエスト' WHERE id = 50;
UPDATE public."JournalGenre" SET name_cn = '日常任务', name_en = 'Daily Quests', name_jp = 'デイリークエスト' WHERE id = 51;
UPDATE public."JournalGenre" SET name_cn = '剧情任务', name_en = 'Main Quests', name_jp = 'ストーリークエスト' WHERE id = 52;
UPDATE public."JournalGenre" SET name_cn = '日常任务', name_en = 'Daily Quests', name_jp = 'デイリークエスト' WHERE id = 53;
UPDATE public."JournalGenre" SET name_cn = '剧情任务', name_en = 'Main Quests', name_jp = 'ストーリークエスト' WHERE id = 54;
UPDATE public."JournalGenre" SET name_cn = '日常任务', name_en = 'Daily Quests', name_jp = 'デイリークエスト' WHERE id = 55;
UPDATE public."JournalGenre" SET name_cn = '剧情任务', name_en = 'Main Quests', name_jp = 'ストーリークエスト' WHERE id = 56;
UPDATE public."JournalGenre" SET name_cn = '日常任务', name_en = 'Daily Quests', name_jp = 'デイリークエスト' WHERE id = 57;
UPDATE public."JournalGenre" SET name_cn = '剧情任务', name_en = 'Main Quests', name_jp = 'ストーリークエスト' WHERE id = 58;
UPDATE public."JournalGenre" SET name_cn = '日常任务', name_en = 'Daily Quests', name_jp = 'デイリークエスト' WHERE id = 59;
UPDATE public."JournalGenre" SET name_cn = '龙诗战争外传', name_en = 'Tales of the Dragonsong War', name_jp = '竜詩戦争 番外編' WHERE id = 60;
UPDATE public."JournalGenre" SET name_cn = '拂晓回归外传', name_en = 'Tales from the Shadows', name_jp = '暁の帰還 番外編' WHERE id = 61;
UPDATE public."JournalGenre" SET name_cn = null, name_en = 'Tales of Newfound Adventure', name_jp = '新たなる冒険 番外編' WHERE id = 62;
UPDATE public."JournalGenre" SET name_cn = '非著名调查员', name_en = 'Hildibrand Quests', name_jp = 'ヒルディブランド' WHERE id = 63;
UPDATE public."JournalGenre" SET name_cn = '非著名调查员：苍穹之章', name_en = 'Further Hildibrand Adventures', name_jp = 'ヒルディブランド 蒼天編' WHERE id = 64;
UPDATE public."JournalGenre" SET name_cn = '非著名调查员：红莲之章', name_en = 'Even Further Hildibrand Adventures', name_jp = 'ヒルディブランド 紅蓮編' WHERE id = 65;
UPDATE public."JournalGenre" SET name_cn = '希尔迪布兰德归来', name_en = 'Somehow Further Hildibrand Adventures', name_jp = '帰ってきたヒルディブランド' WHERE id = 66;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 67;
UPDATE public."JournalGenre" SET name_cn = '黄道武器', name_en = 'Zodiac Weapons', name_jp = 'ゾディアックウェポン' WHERE id = 68;
UPDATE public."JournalGenre" SET name_cn = '元灵武器', name_en = 'Anima Weapons', name_jp = 'アニマウェポン' WHERE id = 69;
UPDATE public."JournalGenre" SET name_cn = '禁地优雷卡', name_en = 'The Forbidden Land, Eureka', name_jp = '禁断の地 エウレカ' WHERE id = 70;
UPDATE public."JournalGenre" SET name_cn = '天佑女王', name_en = 'Resistance Weapons', name_jp = 'セイブ・ザ・クイーン' WHERE id = 71;
UPDATE public."JournalGenre" SET name_cn = '邮差莫古力', name_en = 'Delivery Moogle Quests', name_jp = 'レターモーグリ' WHERE id = 72;
UPDATE public."JournalGenre" SET name_cn = '圣恩达利姆神学院记', name_en = 'Scholasticate Quests', name_jp = '聖アンダリム神学院記' WHERE id = 73;
UPDATE public."JournalGenre" SET name_cn = '虚无界再生计划', name_en = 'Void Quests', name_jp = 'ヴォイド再生計画' WHERE id = 74;
UPDATE public."JournalGenre" SET name_cn = '塔塔露的大繁荣商店', name_en = 'Tataru''s Grand Endeavor', name_jp = 'タタルの大繁盛商店' WHERE id = 75;
UPDATE public."JournalGenre" SET name_cn = '多玛冒险者团', name_en = 'Doman Adventurers'' Guild Quests', name_jp = 'ドマ冒険者団' WHERE id = 76;
UPDATE public."JournalGenre" SET name_cn = '多玛飞地重建记', name_en = 'Doman Reconstruction Quests', name_jp = 'ドマ町人地復興記' WHERE id = 77;
UPDATE public."JournalGenre" SET name_cn = '重建伊修加德：剧情任务', name_en = 'Ishgardian Restoration Main Quests', name_jp = 'イシュガルド復興：ストーリークエスト' WHERE id = 78;
UPDATE public."JournalGenre" SET name_cn = '重建伊修加德：支线任务', name_en = 'Ishgardian Restoration Sidequests', name_jp = 'イシュガルド復興：サブクエスト' WHERE id = 79;
UPDATE public."JournalGenre" SET name_cn = null, name_en = 'Island Sanctuary Quests', name_jp = '無人島開拓記' WHERE id = 80;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 81;
UPDATE public."JournalGenre" SET name_cn = '蛮族盟友', name_en = 'Allied Tribal Quests', name_jp = '友好部族エクストラストーリー' WHERE id = 82;
UPDATE public."JournalGenre" SET name_cn = '蛮族盟友：苍穹之章', name_en = 'Heavensward Tribal Quests', name_jp = '友好部族エクストラストーリー 蒼天編' WHERE id = 83;
UPDATE public."JournalGenre" SET name_cn = '蛮族盟友：红莲之章', name_en = 'Stormblood Tribal Quests', name_jp = '友好部族エクストラストーリー 紅蓮編' WHERE id = 84;
UPDATE public."JournalGenre" SET name_cn = '异国的诗人', name_en = 'Wandering Minstrel Quests', name_jp = '異邦の詩人' WHERE id = 85;
UPDATE public."JournalGenre" SET name_cn = '支线任务：拉诺西亚', name_en = 'La Noscean Sidequests', name_jp = 'サブクエスト：ラノシア' WHERE id = 86;
UPDATE public."JournalGenre" SET name_cn = '支线任务：黑衣森林', name_en = 'Gridanian Sidequests', name_jp = 'サブクエスト：黒衣森' WHERE id = 87;
UPDATE public."JournalGenre" SET name_cn = '支线任务：萨纳兰', name_en = 'Ul''dahn Sidequests', name_jp = 'サブクエスト：ザナラーン' WHERE id = 88;
UPDATE public."JournalGenre" SET name_cn = '支线任务：库尔札斯', name_en = 'Coerthan Sidequests', name_jp = 'サブクエスト：クルザス' WHERE id = 89;
UPDATE public."JournalGenre" SET name_cn = '支线任务：摩杜纳', name_en = 'Mor Dhonan Sidequests', name_jp = 'サブクエスト：モードゥナ' WHERE id = 90;
UPDATE public."JournalGenre" SET name_cn = '支线任务：伊修加德', name_en = 'Ishgardian Sidequests', name_jp = 'サブクエスト：イシュガルド' WHERE id = 91;
UPDATE public."JournalGenre" SET name_cn = '支线任务：阿巴拉提亚云海', name_en = 'Abalathian Sidequests', name_jp = 'サブクエスト：アバラシア雲海' WHERE id = 92;
UPDATE public."JournalGenre" SET name_cn = '支线任务：龙堡参天高地', name_en = 'Dravanian Forelands Sidequests', name_jp = 'サブクエスト：高地ドラヴァニア' WHERE id = 93;
UPDATE public."JournalGenre" SET name_cn = '支线任务：龙堡内陆低地', name_en = 'Dravanian Hinterlands Sidequests', name_jp = 'サブクエスト：低地ドラヴァニア' WHERE id = 94;
UPDATE public."JournalGenre" SET name_cn = '支线任务：翻云雾海', name_en = 'Churning Mists Sidequests', name_jp = 'サブクエスト：ドラヴァニア雲海' WHERE id = 95;
UPDATE public."JournalGenre" SET name_cn = '支线任务：田园郡', name_en = 'Idyllshire Sidequests', name_jp = 'サブクエスト：イディルシャイア' WHERE id = 96;
UPDATE public."JournalGenre" SET name_cn = '支线任务：魔大陆', name_en = 'Azys Lla Sidequests', name_jp = 'サブクエスト：アジス・ラー' WHERE id = 97;
UPDATE public."JournalGenre" SET name_cn = '支线任务：神拳痕', name_en = 'Rhalgr''s Reach Sidequests', name_jp = 'サブクエスト：ラールガーズリーチ' WHERE id = 98;
UPDATE public."JournalGenre" SET name_cn = '支线任务：基拉巴尼亚边区', name_en = 'Fringes Sidequests', name_jp = 'サブクエスト：ギラバニア辺境地帯' WHERE id = 99;
UPDATE public."JournalGenre" SET name_cn = '支线任务：基拉巴尼亚山区', name_en = 'Peaks Sidequests', name_jp = 'サブクエスト：ギラバニア山岳地帯' WHERE id = 100;
UPDATE public."JournalGenre" SET name_cn = '支线任务：基拉巴尼亚湖区', name_en = 'Lochs Sidequests', name_jp = 'サブクエスト：ギラバニア湖畔地帯' WHERE id = 101;
UPDATE public."JournalGenre" SET name_cn = '支线任务：黄金港', name_en = 'Kugane Sidequests', name_jp = 'サブクエスト：クガネ' WHERE id = 102;
UPDATE public."JournalGenre" SET name_cn = '支线任务：红玉海', name_en = 'Ruby Sea Sidequests', name_jp = 'サブクエスト：紅玉海' WHERE id = 103;
UPDATE public."JournalGenre" SET name_cn = '支线任务：延夏', name_en = 'Yanxia Sidequests', name_jp = 'サブクエスト：ヤンサ' WHERE id = 104;
UPDATE public."JournalGenre" SET name_cn = '支线任务：太阳神草原', name_en = 'Azim Steppe Sidequests', name_jp = 'サブクエスト：アジムステップ' WHERE id = 105;
UPDATE public."JournalGenre" SET name_cn = '支线任务：水晶都', name_en = 'Crystarium Sidequests', name_jp = 'サブクエスト：クリスタリウム' WHERE id = 106;
UPDATE public."JournalGenre" SET name_cn = '支线任务：游末邦', name_en = 'Eulmore Sidequests', name_jp = 'サブクエスト：ユールモア' WHERE id = 107;
UPDATE public."JournalGenre" SET name_cn = '支线任务：雷克兰德', name_en = 'Lakeland Sidequests', name_jp = 'サブクエスト：レイクランド' WHERE id = 108;
UPDATE public."JournalGenre" SET name_cn = '支线任务：珂露西亚岛', name_en = 'Kholusia Sidequests', name_jp = 'サブクエスト：コルシア島' WHERE id = 109;
UPDATE public."JournalGenre" SET name_cn = '支线任务：安穆·艾兰', name_en = 'Amh Araeng Sidequests', name_jp = 'サブクエスト：アム・アレーン' WHERE id = 110;
UPDATE public."JournalGenre" SET name_cn = '支线任务：伊尔美格', name_en = 'Il Mheg Sidequests', name_jp = 'サブクエスト：イル・メグ' WHERE id = 111;
UPDATE public."JournalGenre" SET name_cn = '支线任务：拉凯提卡大森林', name_en = 'Rak''tika Sidequests', name_jp = 'サブクエスト：ラケティカ大森林' WHERE id = 112;
UPDATE public."JournalGenre" SET name_cn = '支线任务：黑风海', name_en = 'Tempest Sidequests', name_jp = 'サブクエスト：テンペスト' WHERE id = 113;
UPDATE public."JournalGenre" SET name_cn = '支线任务：旧萨雷安', name_en = 'Old Sharlayan Sidequests', name_jp = 'サブクエスト：オールド・シャーレアン' WHERE id = 114;
UPDATE public."JournalGenre" SET name_cn = '支线任务：拉札罕', name_en = 'Radz-at-Han Sidequests', name_jp = 'サブクエスト：ラザハン' WHERE id = 115;
UPDATE public."JournalGenre" SET name_cn = '支线任务：迷津', name_en = 'Labyrinthos Sidequests', name_jp = 'サブクエスト：ラヴィリンソス' WHERE id = 116;
UPDATE public."JournalGenre" SET name_cn = '支线任务：萨维奈岛', name_en = 'Thavnairian Sidequests', name_jp = 'サブクエスト：サベネア島' WHERE id = 117;
UPDATE public."JournalGenre" SET name_cn = '支线任务：加雷马', name_en = 'Garlean Sidequests', name_jp = 'サブクエスト：ガレマルド' WHERE id = 118;
UPDATE public."JournalGenre" SET name_cn = '支线任务：叹息海', name_en = 'Mare Lamentorum Sidequests', name_jp = 'サブクエスト：嘆きの海' WHERE id = 119;
UPDATE public."JournalGenre" SET name_cn = '支线任务：厄尔庇斯', name_en = 'Elpis Sidequests', name_jp = 'サブクエスト：エルピス' WHERE id = 120;
UPDATE public."JournalGenre" SET name_cn = '支线任务：天外天垓', name_en = 'Ultima Thule Sidequests', name_jp = 'サブクエスト：ウルティマ・トゥーレ' WHERE id = 121;
UPDATE public."JournalGenre" SET name_cn = '剑术师任务', name_en = 'Gladiator Quests', name_jp = '剣術士クエスト' WHERE id = 122;
UPDATE public."JournalGenre" SET name_cn = '格斗家任务', name_en = 'Pugilist Quests', name_jp = '格闘士クエスト' WHERE id = 123;
UPDATE public."JournalGenre" SET name_cn = '斧术师任务', name_en = 'Marauder Quests', name_jp = '斧術士クエスト' WHERE id = 124;
UPDATE public."JournalGenre" SET name_cn = '枪术师任务', name_en = 'Lancer Quests', name_jp = '槍術士クエスト' WHERE id = 125;
UPDATE public."JournalGenre" SET name_cn = '弓箭手任务', name_en = 'Archer Quests', name_jp = '弓術士クエスト' WHERE id = 126;
UPDATE public."JournalGenre" SET name_cn = '双剑师任务', name_en = 'Rogue Quests', name_jp = '双剣士クエスト' WHERE id = 127;
UPDATE public."JournalGenre" SET name_cn = '幻术师任务', name_en = 'Conjurer Quests', name_jp = '幻術士クエスト' WHERE id = 128;
UPDATE public."JournalGenre" SET name_cn = '咒术师任务', name_en = 'Thaumaturge Quests', name_jp = '呪術士クエスト' WHERE id = 129;
UPDATE public."JournalGenre" SET name_cn = '秘术师任务', name_en = 'Arcanist Quests', name_jp = '巴術士クエスト' WHERE id = 130;
UPDATE public."JournalGenre" SET name_cn = '刻木匠任务', name_en = 'Carpenter Quests', name_jp = '木工師クエスト' WHERE id = 131;
UPDATE public."JournalGenre" SET name_cn = '锻铁匠任务', name_en = 'Blacksmith Quests', name_jp = '鍛冶師クエスト' WHERE id = 132;
UPDATE public."JournalGenre" SET name_cn = '铸甲匠任务', name_en = 'Armorer Quests', name_jp = '甲冑師クエスト' WHERE id = 133;
UPDATE public."JournalGenre" SET name_cn = '雕金匠任务', name_en = 'Goldsmith Quests', name_jp = '彫金師クエスト' WHERE id = 134;
UPDATE public."JournalGenre" SET name_cn = '制革匠任务', name_en = 'Leatherworker Quests', name_jp = '革細工師クエスト' WHERE id = 135;
UPDATE public."JournalGenre" SET name_cn = '裁衣匠任务', name_en = 'Weaver Quests', name_jp = '裁縫師クエスト' WHERE id = 136;
UPDATE public."JournalGenre" SET name_cn = '炼金术士任务', name_en = 'Alchemist Quests', name_jp = '錬金術師クエスト' WHERE id = 137;
UPDATE public."JournalGenre" SET name_cn = '烹调师任务', name_en = 'Culinarian Quests', name_jp = '調理師クエスト' WHERE id = 138;
UPDATE public."JournalGenre" SET name_cn = '采矿工任务', name_en = 'Miner Quests', name_jp = '採掘師クエスト' WHERE id = 139;
UPDATE public."JournalGenre" SET name_cn = '园艺工任务', name_en = 'Botanist Quests', name_jp = '園芸師クエスト' WHERE id = 140;
UPDATE public."JournalGenre" SET name_cn = '捕鱼人任务', name_en = 'Fisher Quests', name_jp = '漁師クエスト' WHERE id = 141;
UPDATE public."JournalGenre" SET name_cn = '骑士任务', name_en = 'Paladin Quests', name_jp = 'ナイトクエスト' WHERE id = 142;
UPDATE public."JournalGenre" SET name_cn = '武僧任务', name_en = 'Monk Quests', name_jp = 'モンククエスト' WHERE id = 143;
UPDATE public."JournalGenre" SET name_cn = '战士任务', name_en = 'Warrior Quests', name_jp = '戦士クエスト' WHERE id = 144;
UPDATE public."JournalGenre" SET name_cn = '龙骑士任务', name_en = 'Dragoon Quests', name_jp = '竜騎士クエスト' WHERE id = 145;
UPDATE public."JournalGenre" SET name_cn = '吟游诗人任务', name_en = 'Bard Quests', name_jp = '吟遊詩人クエスト' WHERE id = 146;
UPDATE public."JournalGenre" SET name_cn = '忍者任务', name_en = 'Ninja Quests', name_jp = '忍者クエスト' WHERE id = 147;
UPDATE public."JournalGenre" SET name_cn = '白魔法师任务', name_en = 'White Mage Quests', name_jp = '白魔道士クエスト' WHERE id = 148;
UPDATE public."JournalGenre" SET name_cn = '黑魔法师任务', name_en = 'Black Mage Quests', name_jp = '黒魔道士クエスト' WHERE id = 149;
UPDATE public."JournalGenre" SET name_cn = '召唤师任务', name_en = 'Summoner Quests', name_jp = '召喚士クエスト' WHERE id = 150;
UPDATE public."JournalGenre" SET name_cn = '学者任务', name_en = 'Scholar Quests', name_jp = '学者クエスト' WHERE id = 151;
UPDATE public."JournalGenre" SET name_cn = '暗黑骑士任务', name_en = 'Dark Knight Quests', name_jp = '暗黒騎士クエスト' WHERE id = 152;
UPDATE public."JournalGenre" SET name_cn = '机工士任务', name_en = 'Machinist Quests', name_jp = '機工士クエスト' WHERE id = 153;
UPDATE public."JournalGenre" SET name_cn = '占星术士任务', name_en = 'Astrologian Quests', name_jp = '占星術師クエスト' WHERE id = 154;
UPDATE public."JournalGenre" SET name_cn = '武士任务', name_en = 'Samurai Quests', name_jp = '侍クエスト' WHERE id = 155;
UPDATE public."JournalGenre" SET name_cn = '赤魔法师任务', name_en = 'Red Mage Quests', name_jp = '赤魔道士クエスト' WHERE id = 156;
UPDATE public."JournalGenre" SET name_cn = '绝枪战士任务', name_en = 'Gunbreaker Quests', name_jp = 'ガンブレイカークエスト' WHERE id = 157;
UPDATE public."JournalGenre" SET name_cn = '舞者任务', name_en = 'Dancer Quests', name_jp = '踊り子クエスト' WHERE id = 158;
UPDATE public."JournalGenre" SET name_cn = '贤者任务', name_en = 'Sage Quests', name_jp = '賢者クエスト' WHERE id = 159;
UPDATE public."JournalGenre" SET name_cn = '钐镰客任务', name_en = 'Reaper Quests', name_jp = 'リーパークエスト' WHERE id = 160;
UPDATE public."JournalGenre" SET name_cn = '青魔法师任务', name_en = 'Blue Mage Quests', name_jp = '青魔道士クエスト' WHERE id = 161;
UPDATE public."JournalGenre" SET name_cn = '金属工艺部任务', name_en = 'Facet of Forging Quests', name_jp = '錬鉄科クエスト' WHERE id = 162;
UPDATE public."JournalGenre" SET name_cn = '手工工艺部任务', name_en = 'Facet of Crafting Quests', name_jp = '手工科クエスト' WHERE id = 163;
UPDATE public."JournalGenre" SET name_cn = '食药工艺部任务', name_en = 'Facet of Nourishing Quests', name_jp = '食薬科クエスト' WHERE id = 164;
UPDATE public."JournalGenre" SET name_cn = '大地资源部任务', name_en = 'Facet of Gathering Quests', name_jp = '調達科クエスト' WHERE id = 165;
UPDATE public."JournalGenre" SET name_cn = '水生资源部任务', name_en = 'Facet of Fishing Quests', name_jp = '漁業科クエスト' WHERE id = 166;
UPDATE public."JournalGenre" SET name_cn = '中庸工艺馆剧情任务', name_en = 'Crystalline Mean Quests', name_jp = 'ミーン工芸館エクストラストーリー' WHERE id = 167;
UPDATE public."JournalGenre" SET name_cn = '考古系任务', name_en = 'Faculty of Archaeology Quests', name_jp = '考古学部クエスト' WHERE id = 168;
UPDATE public."JournalGenre" SET name_cn = '天文系任务', name_en = 'Faculty of Astronomy Quests', name_jp = '天文学部クエスト' WHERE id = 169;
UPDATE public."JournalGenre" SET name_cn = '医学系任务', name_en = 'Faculty of Medicine Quests', name_jp = '医学部クエスト' WHERE id = 170;
UPDATE public."JournalGenre" SET name_cn = '文化系任务', name_en = 'Faculty of Anthropology Quests', name_jp = '文化学部クエスト' WHERE id = 171;
UPDATE public."JournalGenre" SET name_cn = '以太系任务', name_en = 'Faculty of Aetherology Quests', name_jp = 'エーテル学部クエスト' WHERE id = 172;
UPDATE public."JournalGenre" SET name_cn = '萨雷安魔法大学剧情任务', name_en = 'Studium Quests', name_jp = '魔法大学エクストラストーリー' WHERE id = 173;
UPDATE public."JournalGenre" SET name_cn = '防护职能任务', name_en = 'Tank Role Quests (Shadowbringers)', name_jp = 'TANKロールクエスト' WHERE id = 174;
UPDATE public."JournalGenre" SET name_cn = '治疗职能任务', name_en = 'Healer Role Quests (Shadowbringers)', name_jp = 'HEALERロールクエスト' WHERE id = 175;
UPDATE public."JournalGenre" SET name_cn = '物理进攻职能任务', name_en = 'Physical DPS Role Quests (Shadowbringers)', name_jp = 'ファイター系DPSロールクエスト' WHERE id = 176;
UPDATE public."JournalGenre" SET name_cn = '魔法进攻职能任务', name_en = 'Magical Ranged DPS Role Quests (Shadowbringers)', name_jp = 'ソーサラー系DPSロールクエスト' WHERE id = 177;
UPDATE public."JournalGenre" SET name_cn = '职能剧情任务', name_en = 'Role Quests (Shadowbringers)', name_jp = 'ロールエクストラストーリー' WHERE id = 178;
UPDATE public."JournalGenre" SET name_cn = '防护职能任务：晓月之章', name_en = 'Tank Role Quests (Endwalker)', name_jp = 'TANKロールクエスト 暁月編' WHERE id = 179;
UPDATE public."JournalGenre" SET name_cn = '治疗职能任务：晓月之章', name_en = 'Healer Role Quests (Endwalker)', name_jp = 'HEALERロールクエスト 暁月編' WHERE id = 180;
UPDATE public."JournalGenre" SET name_cn = '近战职能任务：晓月之章', name_en = 'Melee DPS Role Quests (Endwalker)', name_jp = '近接物理DPSロールクエスト 暁月編' WHERE id = 181;
UPDATE public."JournalGenre" SET name_cn = '远程物理职能任务：晓月之章', name_en = 'Physical Ranged DPS Role Quests (Endwalker)', name_jp = '遠隔物理DPSロールクエスト 暁月編' WHERE id = 182;
UPDATE public."JournalGenre" SET name_cn = '远程魔法职能任务：晓月之章', name_en = 'Magical Ranged DPS Role Quests (Endwalker)', name_jp = '遠隔魔法DPSロールクエスト 暁月編' WHERE id = 183;
UPDATE public."JournalGenre" SET name_cn = '职能剧情任务：晓月之章', name_en = 'Role Quests (Endwalker)', name_jp = 'ロールエクストラストーリー 暁月編' WHERE id = 184;
UPDATE public."JournalGenre" SET name_cn = '黑涡团任务', name_en = 'Maelstrom Quests', name_jp = '黒渦団クエスト' WHERE id = 185;
UPDATE public."JournalGenre" SET name_cn = '双蛇党任务', name_en = 'Order of the Twin Adder Quests', name_jp = '双蛇党クエスト' WHERE id = 186;
UPDATE public."JournalGenre" SET name_cn = '恒辉队任务', name_en = 'Immortal Flames Quests', name_jp = '不滅隊クエスト' WHERE id = 187;
UPDATE public."JournalGenre" SET name_cn = '季节活动', name_en = 'Seasonal Events', name_jp = 'シーズナルクエスト' WHERE id = 188;
UPDATE public."JournalGenre" SET name_cn = '降神节', name_en = 'Heavensturn Events', name_jp = '降神祭' WHERE id = 189;
UPDATE public."JournalGenre" SET name_cn = '东节', name_en = 'Eastern Duties', name_jp = 'CHS／KO専用' WHERE id = 190;
UPDATE public."JournalGenre" SET name_cn = '恋人节', name_en = 'Valentione''s Day Events', name_jp = 'ヴァレンティオンデー' WHERE id = 191;
UPDATE public."JournalGenre" SET name_cn = '恋人节&女儿节', name_en = 'Valentione''s & Little Ladies'' Day Events', name_jp = 'ヴァレンティオン＆プリンセスデー' WHERE id = 192;
UPDATE public."JournalGenre" SET name_cn = '女儿节', name_en = 'Little Ladies'' Day Events', name_jp = 'プリンセスデー' WHERE id = 193;
UPDATE public."JournalGenre" SET name_cn = '彩蛋狩猎', name_en = 'Egg Hunts', name_jp = 'エッグハント' WHERE id = 194;
UPDATE public."JournalGenre" SET name_cn = '金碟嘉年华', name_en = 'Gold Saucer Festivities', name_jp = 'ゴールドソーサー・フェスティバル' WHERE id = 195;
UPDATE public."JournalGenre" SET name_cn = '红莲节', name_en = 'Moonfire Faire Events', name_jp = '紅蓮祭' WHERE id = 196;
UPDATE public."JournalGenre" SET name_cn = '新生庆典', name_en = 'Rising Events', name_jp = '新生祭' WHERE id = 197;
UPDATE public."JournalGenre" SET name_cn = '守护天节', name_en = 'All Saints'' Wake Events', name_jp = '守護天節' WHERE id = 198;
UPDATE public."JournalGenre" SET name_cn = '星芒节', name_en = 'Starlight Celebration Events', name_jp = '星芒祭' WHERE id = 199;
UPDATE public."JournalGenre" SET name_cn = '其他季节活动', name_en = 'Other Seasonal Events', name_jp = 'その他シーズナルイベント' WHERE id = 200;
UPDATE public."JournalGenre" SET name_cn = '纪念任务', name_en = 'Special Quests', name_jp = 'スペシャルクエスト' WHERE id = 201;
UPDATE public."JournalGenre" SET name_cn = '来访者任务', name_en = 'Collaboration Quests', name_jp = '来訪者クエスト' WHERE id = 202;
UPDATE public."JournalGenre" SET name_cn = '佣兵理符任务', name_en = 'Battlecraft Levequests', name_jp = '傭兵リーヴ' WHERE id = 203;
UPDATE public."JournalGenre" SET name_cn = '刻木匠理符任务', name_en = 'Carpenter Levequests', name_jp = '木工師リーヴ' WHERE id = 204;
UPDATE public."JournalGenre" SET name_cn = '锻铁匠理符任务', name_en = 'Blacksmith Levequests', name_jp = '鍛冶師リーヴ' WHERE id = 205;
UPDATE public."JournalGenre" SET name_cn = '铸甲匠理符任务', name_en = 'Armorer Levequests', name_jp = '甲冑師リーヴ' WHERE id = 206;
UPDATE public."JournalGenre" SET name_cn = '雕金匠理符任务', name_en = 'Goldsmith Levequests', name_jp = '彫金師リーヴ' WHERE id = 207;
UPDATE public."JournalGenre" SET name_cn = '制革匠理符任务', name_en = 'Leatherworker Levequests', name_jp = '革細工師リーヴ' WHERE id = 208;
UPDATE public."JournalGenre" SET name_cn = '裁衣匠理符任务', name_en = 'Weaver Levequests', name_jp = '裁縫師リーヴ' WHERE id = 209;
UPDATE public."JournalGenre" SET name_cn = '炼金术士理符任务', name_en = 'Alchemist Levequests', name_jp = '錬金術師リーヴ' WHERE id = 210;
UPDATE public."JournalGenre" SET name_cn = '烹调师理符任务', name_en = 'Culinarian Levequests', name_jp = '調理師リーヴ' WHERE id = 211;
UPDATE public."JournalGenre" SET name_cn = '采矿工理符任务', name_en = 'Miner Levequests', name_jp = '採掘師リーヴ' WHERE id = 212;
UPDATE public."JournalGenre" SET name_cn = '园艺工理符任务', name_en = 'Botanist Levequests', name_jp = '園芸師リーヴ' WHERE id = 213;
UPDATE public."JournalGenre" SET name_cn = '捕鱼人理符任务', name_en = 'Fisher Levequests', name_jp = '漁師リーヴ' WHERE id = 214;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 215;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 216;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 217;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 218;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 219;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 220;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 221;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 222;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 223;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 224;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 225;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 226;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 227;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 228;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 229;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 230;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 231;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 232;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 233;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 234;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 235;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 236;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 237;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 238;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 239;
UPDATE public."JournalGenre" SET name_cn = '黑涡团理符任务', name_en = 'Maelstrom Levequests', name_jp = '黒渦団リーヴ' WHERE id = 240;
UPDATE public."JournalGenre" SET name_cn = '双蛇党理符任务', name_en = 'Order of the Twin Adder Levequests', name_jp = '双蛇党リーヴ' WHERE id = 241;
UPDATE public."JournalGenre" SET name_cn = '恒辉队理符任务', name_en = 'Immortal Flames Levequests', name_jp = '不滅隊リーヴ' WHERE id = 242;
UPDATE public."JournalGenre" SET name_cn = '迷宫挑战', name_en = 'Instanced Dungeons', name_jp = 'ダンジョン' WHERE id = 243;
UPDATE public."JournalGenre" SET name_cn = '大型任务', name_en = 'Instanced Raids', name_jp = 'レイド' WHERE id = 244;
UPDATE public."JournalGenre" SET name_cn = '讨伐歼灭战', name_en = 'Trials', name_jp = '討伐・討滅戦' WHERE id = 245;
UPDATE public."JournalGenre" SET name_cn = '深层迷宫', name_en = 'Deep Dungeons', name_jp = 'ディープダンジョン' WHERE id = 246;
UPDATE public."JournalGenre" SET name_cn = '禁地优雷卡', name_en = 'Eureka Expedition Quests', name_jp = '禁断の地 エウレカ' WHERE id = 247;
UPDATE public."JournalGenre" SET name_cn = '天佑女王', name_en = 'Save the Queen: Blades of Gunnhildr', name_jp = 'セイブ・ザ・クイーン' WHERE id = 248;
UPDATE public."JournalGenre" SET name_cn = null, name_en = null, name_jp = null WHERE id = 249;
UPDATE public."JournalGenre" SET name_cn = '行会令', name_en = 'Guildhests', name_jp = 'ギルドオーダー' WHERE id = 250;
UPDATE public."JournalGenre" SET name_cn = '主线剧情任务：第六星历', name_en = 'Legacy Main Scenario Quests', name_jp = 'メインクエスト：レガシー' WHERE id = 251;
UPDATE public."JournalGenre" SET name_cn = '支线任务：第六星历', name_en = 'Legacy Sidequests', name_jp = 'サブクエスト：レガシー' WHERE id = 252;
UPDATE public."JournalGenre" SET name_cn = '职业任务：第六星历', name_en = 'Legacy Class Quests', name_jp = 'クラスクエスト：レガシー' WHERE id = 253;
UPDATE public."JournalGenre" SET name_cn = '特职任务：第六星历', name_en = 'Legacy Job Quests', name_jp = 'ジョブクエスト：レガシー' WHERE id = 254;
UPDATE public."JournalGenre" SET name_cn = '军队任务：第六星历', name_en = 'Legacy Grand Company Quests', name_jp = 'グランドカンパニークエスト：レガシー' WHERE id = 255;
