UPDATE public."JournalCategory" SET name_cn = '无效分类', name_en = 'Sephiroth Missions', name_jp = '無効カテゴリ' WHERE id = 0;
UPDATE public."JournalCategory" SET name_cn = '重生之境主线任务', name_en = 'Seventh Umbral Era Main Scenario Quests', name_jp = 'メインクエスト：新生エオルゼア' WHERE id = 1;
UPDATE public."JournalCategory" SET name_cn = '第七星历主线任务', name_en = 'Seventh Astral Era Main Scenario Quests', name_jp = 'メインクエスト：第七星暦ストーリー' WHERE id = 2;
UPDATE public."JournalCategory" SET name_cn = '苍穹之禁城主线任务', name_en = 'Heavensward Main Scenario Quests', name_jp = 'メインクエスト：蒼天のイシュガルド' WHERE id = 3;
UPDATE public."JournalCategory" SET name_cn = '龙诗战争终章主线任务', name_en = 'Dragonsong Main Scenario Quests', name_jp = 'メインクエスト：竜詩戦争 完結編' WHERE id = 4;
UPDATE public."JournalCategory" SET name_cn = '龙诗战争尾声主线任务', name_en = 'Post-Dragonsong Main Scenario Quests', name_jp = 'メインクエスト：竜詩戦争 戦後編' WHERE id = 5;
UPDATE public."JournalCategory" SET name_cn = '红莲之狂潮主线任务', name_en = 'Stormblood Main Scenario Quests', name_jp = 'メインクエスト：紅蓮のリベレーター' WHERE id = 6;
UPDATE public."JournalCategory" SET name_cn = '解放战争战后主线任务', name_en = 'Post-Stormblood Main Scenario Quests', name_jp = 'メインクエスト：解放戦争 戦後編' WHERE id = 7;
UPDATE public."JournalCategory" SET name_cn = '暗影之逆焰主线任务', name_en = 'Shadowbringers Main Scenario Quests', name_jp = 'メインクエスト：漆黒のヴィランズ' WHERE id = 8;
UPDATE public."JournalCategory" SET name_cn = '拂晓回归主线任务', name_en = 'Post-Shadowbringers Main Scenario Quests', name_jp = 'メインクエスト：暁の帰還編' WHERE id = 9;
UPDATE public."JournalCategory" SET name_cn = '末日序曲主线任务', name_en = 'Post-Shadowbringers Main Scenario Quests II', name_jp = 'メインクエスト：終末の序曲編' WHERE id = 10;
UPDATE public."JournalCategory" SET name_cn = '晓月之终途主线任务', name_en = 'Endwalker Main Scenario Quests', name_jp = 'メインクエスト：暁月のフィナーレ' WHERE id = 11;
UPDATE public."JournalCategory" SET name_cn = '崭新的冒险主线任务', name_en = 'Post-Endwalker Main Scenario Quests', name_jp = 'メインクエスト：新たなる冒険編' WHERE id = 12;
UPDATE public."JournalCategory" SET name_cn = '第七星历编年史：蛮神', name_en = 'Chronicles of a New Era - Primals', name_jp = 'クロニクルクエスト：蛮神の脅威' WHERE id = 13;
UPDATE public."JournalCategory" SET name_cn = '第七星历编年史：巴哈姆特', name_en = 'Chronicles of a New Era - Bahamut', name_jp = 'クロニクルクエスト：バハムート' WHERE id = 14;
UPDATE public."JournalCategory" SET name_cn = '第七星历编年史：水晶塔', name_en = 'Chronicles of a New Era - The Crystal Tower', name_jp = 'クロニクルクエスト：クリスタルタワー' WHERE id = 15;
UPDATE public."JournalCategory" SET name_cn = '第七星历编年史：亚历山大', name_en = 'Chronicles of a New Era - Alexander', name_jp = 'クロニクルクエスト：アレキサンダー' WHERE id = 16;
UPDATE public."JournalCategory" SET name_cn = '第七星历编年史：上古众神', name_en = 'Chronicles of a New Era - The Warring Triad', name_jp = 'クロニクルクエスト：古の神々' WHERE id = 17;
UPDATE public."JournalCategory" SET name_cn = '第七星历编年史：玛哈之影', name_en = 'Chronicles of a New Era - The Shadow of Mhach', name_jp = 'クロニクルクエスト：シャドウ・オブ・マハ' WHERE id = 18;
UPDATE public."JournalCategory" SET name_cn = '第七星历编年史：欧米茄', name_en = 'Chronicles of a New Era - Omega', name_jp = 'クロニクルクエスト：オメガ' WHERE id = 19;
UPDATE public."JournalCategory" SET name_cn = '第七星历编年史：重返伊瓦利斯', name_en = 'Chronicles of a New Era - Return to Ivalice', name_jp = 'クロニクルクエスト：リターン・トゥ・イヴァリース' WHERE id = 20;
UPDATE public."JournalCategory" SET name_cn = '第七星历编年史：四圣兽奇谭', name_en = 'Chronicles of a New Era - The Four Lords', name_jp = 'クロニクルクエスト：四聖獣奇譚' WHERE id = 21;
UPDATE public."JournalCategory" SET name_cn = '第七星历编年史：伊甸', name_en = 'Chronicles of a New Era - Eden', name_jp = 'クロニクルクエスト：エデン' WHERE id = 22;
UPDATE public."JournalCategory" SET name_cn = '寄叶异闻：暗黑天启', name_en = 'YoRHa: Dark Apocalypse', name_jp = 'YoRHa: Dark Apocalypse' WHERE id = 23;
UPDATE public."JournalCategory" SET name_cn = '第七星历编年史：维尔利特战役', name_en = 'Chronicles of a New Era - The Sorrow of Werlyt', name_jp = 'クロニクルクエスト：ウェルリト戦役' WHERE id = 24;
UPDATE public."JournalCategory" SET name_cn = '第七星历编年史：万魔殿', name_en = 'Chronicles of a New Era - Pandæmonium', name_jp = 'クロニクルクエスト：パンデモニウム' WHERE id = 25;
UPDATE public."JournalCategory" SET name_cn = '第七星历编年史：艾欧泽亚神话', name_en = 'Chronicles of a New Era - Myths of the Realm', name_jp = 'クロニクルクエスト：ミソロジー・オブ・エオルゼア' WHERE id = 26;
UPDATE public."JournalCategory" SET name_cn = null, name_en = '友好部族クエスト：オミクロン族', name_jp = '友好部族クエスト：オミクロン族' WHERE id = 27;
UPDATE public."JournalCategory" SET name_cn = '悌阳象族任务', name_en = 'Arkasodara Quests', name_jp = '友好部族クエスト：アルカソーダラ族' WHERE id = 28;
UPDATE public."JournalCategory" SET name_cn = '蜥蜴人族任务', name_en = 'Amalj''aa Quests', name_jp = '友好部族クエスト：アマルジャ族' WHERE id = 29;
UPDATE public."JournalCategory" SET name_cn = '妖精族任务', name_en = 'Sylph Quests', name_jp = '友好部族クエスト：シルフ族' WHERE id = 30;
UPDATE public."JournalCategory" SET name_cn = '地灵族任务', name_en = 'Kobold Quests', name_jp = '友好部族クエスト：コボルド族' WHERE id = 31;
UPDATE public."JournalCategory" SET name_cn = '鱼人族任务', name_en = 'Sahagin Quests', name_jp = '友好部族クエスト：サハギン族' WHERE id = 32;
UPDATE public."JournalCategory" SET name_cn = '鸟人族任务', name_en = 'Ixal Quests', name_jp = '友好部族クエスト：イクサル族' WHERE id = 33;
UPDATE public."JournalCategory" SET name_cn = '瓦努族任务', name_en = 'Vanu Vanu Quests', name_jp = '友好部族クエスト：バヌバヌ族' WHERE id = 34;
UPDATE public."JournalCategory" SET name_cn = '骨颌族任务', name_en = 'Vath Quests', name_jp = '友好部族クエスト：グナース族' WHERE id = 35;
UPDATE public."JournalCategory" SET name_cn = '莫古力族任务', name_en = 'Moogle Quests', name_jp = '友好部族クエスト：モーグリ族' WHERE id = 36;
UPDATE public."JournalCategory" SET name_cn = '甲人族任务', name_en = 'Kojin Quests', name_jp = '友好部族クエスト：コウジン族' WHERE id = 37;
UPDATE public."JournalCategory" SET name_cn = '阿难陀族任务', name_en = 'Ananta Quests', name_jp = '友好部族クエスト：アナンタ族' WHERE id = 38;
UPDATE public."JournalCategory" SET name_cn = '鲶鱼精族任务', name_en = 'Namazu Quests', name_jp = '友好部族クエスト：ナマズオ族' WHERE id = 39;
UPDATE public."JournalCategory" SET name_cn = '仙子族任务', name_en = 'Pixie Quests', name_jp = '友好部族クエスト：ピクシー族' WHERE id = 40;
UPDATE public."JournalCategory" SET name_cn = '奇塔利族任务', name_en = 'Qitari Quests', name_jp = '友好部族クエスト：キタリ族' WHERE id = 41;
UPDATE public."JournalCategory" SET name_cn = '矮人族任务', name_en = 'Dwarf Quests', name_jp = '友好部族クエスト：ドワーフ族' WHERE id = 42;
UPDATE public."JournalCategory" SET name_cn = '支线剧情任务', name_en = 'Side Story Quests', name_jp = 'サブストーリークエスト' WHERE id = 43;
UPDATE public."JournalCategory" SET name_cn = '拉诺西亚支线任务', name_en = 'Lominsan Sidequests', name_jp = 'サブクエスト：ラノシア' WHERE id = 44;
UPDATE public."JournalCategory" SET name_cn = '黑衣森林支线任务', name_en = 'Gridanian Sidequests', name_jp = 'サブクエスト：黒衣森' WHERE id = 45;
UPDATE public."JournalCategory" SET name_cn = '萨纳兰支线任务', name_en = 'Ul''dahn Sidequests', name_jp = 'サブクエスト：ザナラーン' WHERE id = 46;
UPDATE public."JournalCategory" SET name_cn = '库尔札斯支线任务', name_en = 'Coerthan Sidequests', name_jp = 'サブクエスト：クルザス' WHERE id = 47;
UPDATE public."JournalCategory" SET name_cn = '摩杜纳支线任务', name_en = 'Mor Dhonan Sidequests', name_jp = 'サブクエスト：モードゥナ' WHERE id = 48;
UPDATE public."JournalCategory" SET name_cn = '伊修加德支线任务', name_en = 'Ishgardian Sidequests', name_jp = 'サブクエスト：イシュガルド' WHERE id = 49;
UPDATE public."JournalCategory" SET name_cn = '阿巴拉提亚支线任务', name_en = 'Abalathian Sidequests', name_jp = 'サブクエスト：アバラシア' WHERE id = 50;
UPDATE public."JournalCategory" SET name_cn = '龙堡支线任务', name_en = 'Dravanian Sidequests', name_jp = 'サブクエスト：ドラヴァニア' WHERE id = 51;
UPDATE public."JournalCategory" SET name_cn = '魔大陆支线任务', name_en = 'Azys Lla Sidequests', name_jp = 'サブクエスト：アジス・ラー' WHERE id = 52;
UPDATE public."JournalCategory" SET name_cn = '基拉巴尼亚支线任务', name_en = 'Gyr Abanian Sidequests', name_jp = 'サブクエスト：ギラバニア' WHERE id = 53;
UPDATE public."JournalCategory" SET name_cn = '奥萨德支线任务', name_en = 'Othardian Sidequests', name_jp = 'サブクエスト：オサード' WHERE id = 54;
UPDATE public."JournalCategory" SET name_cn = '远东之国支线任务', name_en = 'Hingan Sidequests', name_jp = 'サブクエスト：ひんがしの国' WHERE id = 55;
UPDATE public."JournalCategory" SET name_cn = '雷克兰德支线任务', name_en = 'Lakeland Sidequests', name_jp = 'サブクエスト：レイクランド' WHERE id = 56;
UPDATE public."JournalCategory" SET name_cn = '珂露西亚岛支线任务', name_en = 'Kholusian Sidequests', name_jp = 'サブクエスト：コルシア島' WHERE id = 57;
UPDATE public."JournalCategory" SET name_cn = '安穆·艾兰支线任务', name_en = 'Amh Araeng Sidequests', name_jp = 'サブクエスト：アム・アレーン' WHERE id = 58;
UPDATE public."JournalCategory" SET name_cn = '伊尔美格支线任务', name_en = 'Il Mheg Sidequests', name_jp = 'サブクエスト：イル・メグ' WHERE id = 59;
UPDATE public."JournalCategory" SET name_cn = '拉凯提卡大森林支线任务', name_en = 'Rak''tika Sidequests', name_jp = 'サブクエスト：ラケティカ大森林' WHERE id = 60;
UPDATE public."JournalCategory" SET name_cn = '黑风海支线任务', name_en = 'Tempest Sidequests', name_jp = 'サブクエスト：テンペスト' WHERE id = 61;
UPDATE public."JournalCategory" SET name_cn = '萨雷安支线任务', name_en = 'Sharlayan Sidequests', name_jp = 'サブクエスト：シャーレアン' WHERE id = 62;
UPDATE public."JournalCategory" SET name_cn = '萨维奈岛支线任务', name_en = 'Thavnairian Sidequests', name_jp = 'サブクエスト：サベネア島' WHERE id = 63;
UPDATE public."JournalCategory" SET name_cn = '加雷马支线任务', name_en = 'Garlean Sidequests', name_jp = 'サブクエスト：ガレマルド' WHERE id = 64;
UPDATE public."JournalCategory" SET name_cn = '叹息海支线任务', name_en = 'Mare Lamentorum Sidequests', name_jp = 'サブクエスト：嘆きの海' WHERE id = 65;
UPDATE public."JournalCategory" SET name_cn = '厄尔庇斯支线任务', name_en = 'Elpis Sidequests', name_jp = 'サブクエスト：エルピス' WHERE id = 66;
UPDATE public."JournalCategory" SET name_cn = '天外天垓支线任务', name_en = 'Ultima Thule Sidequests', name_jp = 'サブクエスト：ウルティマ・トゥーレ' WHERE id = 67;
UPDATE public."JournalCategory" SET name_cn = '战斗精英职业任务', name_en = 'Disciple of War Quests', name_jp = 'クラスクエスト：ファイター' WHERE id = 68;
UPDATE public."JournalCategory" SET name_cn = '魔法导师职业任务', name_en = 'Disciple of Magic Quests', name_jp = 'クラスクエスト：ソーサラー' WHERE id = 69;
UPDATE public."JournalCategory" SET name_cn = '能工巧匠职业任务', name_en = 'Disciple of the Hand Quests', name_jp = 'クラスクエスト：クラフター' WHERE id = 70;
UPDATE public."JournalCategory" SET name_cn = '大地使者职业任务', name_en = 'Disciple of the Land Quests', name_jp = 'クラスクエスト：ギャザラー' WHERE id = 71;
UPDATE public."JournalCategory" SET name_cn = '中庸工艺馆交易职业任务', name_en = 'Crystalline Mean Quests', name_jp = 'クラスクエスト：ミーン工芸館取引' WHERE id = 72;
UPDATE public."JournalCategory" SET name_cn = '萨雷安魔法大学交易职业任务', name_en = 'Studium Quests', name_jp = 'クラスクエスト：魔法大学取引' WHERE id = 73;
UPDATE public."JournalCategory" SET name_cn = '战斗精英特职任务', name_en = 'Disciple of War Job Quests', name_jp = 'ジョブクエスト：ファイター' WHERE id = 74;
UPDATE public."JournalCategory" SET name_cn = '魔法导师特职任务', name_en = 'Disciple of Magic Job Quests', name_jp = 'ジョブクエスト：ソーサラー' WHERE id = 75;
UPDATE public."JournalCategory" SET name_cn = '职能任务', name_en = 'Role Quests', name_jp = 'ロールクエスト' WHERE id = 76;
UPDATE public."JournalCategory" SET name_cn = '军队任务', name_en = 'Grand Company Quests', name_jp = 'グランドカンパニークエスト' WHERE id = 77;
UPDATE public."JournalCategory" SET name_cn = '季节活动', name_en = 'Seasonal Events', name_jp = 'シーズナルイベント' WHERE id = 78;
UPDATE public."JournalCategory" SET name_cn = '其他任务', name_en = 'Special Quests', name_jp = 'エトセトラクエスト' WHERE id = 79;
UPDATE public."JournalCategory" SET name_cn = '佣兵理符', name_en = 'Battlecraft Leves', name_jp = 'リーヴ：傭兵稼業' WHERE id = 80;
UPDATE public."JournalCategory" SET name_cn = '采矿理符', name_en = 'Mining Leves', name_jp = 'リーヴ：採掘師' WHERE id = 81;
UPDATE public."JournalCategory" SET name_cn = '园艺理符', name_en = 'Botany Leves', name_jp = 'リーヴ：園芸師' WHERE id = 82;
UPDATE public."JournalCategory" SET name_cn = '钓鱼理符', name_en = 'Fishing Leves', name_jp = 'リーヴ：漁師' WHERE id = 83;
UPDATE public."JournalCategory" SET name_cn = '木工理符', name_en = 'Carpentry Leves', name_jp = 'リーヴ：木工師' WHERE id = 84;
UPDATE public."JournalCategory" SET name_cn = '锻冶理符', name_en = 'Blacksmithing Leves', name_jp = 'リーヴ：鍛冶師' WHERE id = 85;
UPDATE public."JournalCategory" SET name_cn = '铸甲理符', name_en = 'Armoring Leves', name_jp = 'リーヴ：甲冑師' WHERE id = 86;
UPDATE public."JournalCategory" SET name_cn = '雕金理符', name_en = 'Goldsmithing Leves', name_jp = 'リーヴ：彫金師' WHERE id = 87;
UPDATE public."JournalCategory" SET name_cn = '制革理符', name_en = 'Leatherworking Leves', name_jp = 'リーヴ：革細工師' WHERE id = 88;
UPDATE public."JournalCategory" SET name_cn = '裁缝理符', name_en = 'Clothcrafting Leves', name_jp = 'リーヴ：裁縫師' WHERE id = 89;
UPDATE public."JournalCategory" SET name_cn = '炼金理符', name_en = 'Alchemy Leves', name_jp = 'リーヴ：錬金術師' WHERE id = 90;
UPDATE public."JournalCategory" SET name_cn = '烹调理符', name_en = 'Cooking Leves', name_jp = 'リーヴ：調理師' WHERE id = 91;
UPDATE public."JournalCategory" SET name_cn = '神殿骑士团佣兵理符', name_en = 'Ishgardian Battlecraft Leves', name_jp = '神殿騎士団リーヴ：傭兵稼業' WHERE id = 92;
UPDATE public."JournalCategory" SET name_cn = '神殿骑士团采矿理符', name_en = 'Ishgardian Mining Leves', name_jp = '神殿騎士団リーヴ：採掘師' WHERE id = 93;
UPDATE public."JournalCategory" SET name_cn = '神殿骑士团园艺理符', name_en = 'Ishgardian Botany Leves', name_jp = '神殿騎士団リーヴ：園芸師' WHERE id = 94;
UPDATE public."JournalCategory" SET name_cn = '神殿骑士团钓鱼理符', name_en = 'Ishgardian Fishing Leves', name_jp = '神殿騎士団リーヴ：漁師' WHERE id = 95;
UPDATE public."JournalCategory" SET name_cn = '神殿骑士团木工理符', name_en = 'Ishgardian Carpentry Leves', name_jp = '神殿騎士団リーヴ：木工師' WHERE id = 96;
UPDATE public."JournalCategory" SET name_cn = '神殿骑士团锻冶理符', name_en = 'Ishgardian Blacksmithing Leves', name_jp = '神殿騎士団リーヴ：鍛冶師' WHERE id = 97;
UPDATE public."JournalCategory" SET name_cn = '神殿骑士团铸甲理符', name_en = 'Ishgardian Armoring Leves', name_jp = '神殿騎士団リーヴ：甲冑師' WHERE id = 98;
UPDATE public."JournalCategory" SET name_cn = '神殿骑士团雕金理符', name_en = 'Ishgardian Goldsmithing Leves', name_jp = '神殿騎士団リーヴ：彫金師' WHERE id = 99;
UPDATE public."JournalCategory" SET name_cn = '神殿骑士团制革理符', name_en = 'Ishgardian Leatherworking Leves', name_jp = '神殿騎士団リーヴ：革細工師' WHERE id = 100;
UPDATE public."JournalCategory" SET name_cn = '神殿骑士团裁缝理符', name_en = 'Ishgardian Clothcrafting Leves', name_jp = '神殿騎士団リーヴ：裁縫師' WHERE id = 101;
UPDATE public."JournalCategory" SET name_cn = '神殿骑士团炼金理符', name_en = 'Ishgardian Alchemy Leves', name_jp = '神殿騎士団リーヴ：錬金術師' WHERE id = 102;
UPDATE public."JournalCategory" SET name_cn = '神殿骑士团烹调理符', name_en = 'Ishgardian Cooking Leves', name_jp = '神殿騎士団リーヴ：調理師' WHERE id = 103;
UPDATE public."JournalCategory" SET name_cn = '特殊部队理符', name_en = 'Faction Leves', name_jp = 'ギルドリーヴ：ファクション' WHERE id = 104;
UPDATE public."JournalCategory" SET name_cn = '军队理符', name_en = 'Company Leves', name_jp = 'グランドカンパニーリーヴ' WHERE id = 105;
UPDATE public."JournalCategory" SET name_cn = '迷宫挑战', name_en = 'Instanced Dungeons', name_jp = 'コンテンツ：ダンジョン' WHERE id = 106;
UPDATE public."JournalCategory" SET name_cn = '大型任务', name_en = 'Instanced Raids', name_jp = 'コンテンツ：レイド' WHERE id = 107;
UPDATE public."JournalCategory" SET name_cn = '讨伐歼灭战', name_en = 'Instanced Battles', name_jp = 'コンテンツ：討伐・討滅戦' WHERE id = 108;
UPDATE public."JournalCategory" SET name_cn = '其他任务', name_en = 'Other Duties', name_jp = 'コンテンツ：その他' WHERE id = 109;
UPDATE public."JournalCategory" SET name_cn = '遗产任务', name_en = 'Legacy Quests', name_jp = 'レガシークエスト' WHERE id = 110;
